### ISSUE TITLE
Possibility of determining name of file being checked in *_GetLocList?

### ISSUE THREAD

**Issue by faceleg** [scrooloose/syntastic#1277]
I'd like to modify the javascript - flow checker to only add errors pertinent to the file being currently checked.

Is it possible to determine the filename of the file being checked within the *_GetLocList function?

If I knew the filename I could presumably filter out errors pertinent to other files.

I would like to do this because flow will helpfully indicate why an error occurs, even when the cause is in another file. This causes Vim to jump about, and sometimes underline the wrong part of a file, which is distracting and annoying.

**Comment by lcd047** [comment]
You can get the buffer number with `bufnr('')` and expand it, but the problem you describe is interesting in general, you don't want to restrict the solution to the `flow` checker.

At some point there used to be an option to do exactly what you want, but as I recall it has been superseded by `quiet_messages`, and we can't really go back.  Now, `quiet_messages` does solve the problem for things like errors in C header files, but it doesn't handle your case since the names of the "foreign" files don't have anything special to hook on.  Thus the solution seems to be to extend `quiet_messages`.
 
Please apply c472ec1 and read the corresponding [docs](https://github.com/scrooloose/syntastic/blob/master/doc/syntastic.txt#L482-L522).  The commit changes `quiet_messages` in two ways:
 
* it allows you to negate the filters, by adding a bang before the keys;
* it allows you to add file modifiers such as `:p` to `file` filters.

With this, you can now do something like this:
```vim
autocmd BufEnter *.js let g:syntastic_javascript_flow_quiet_messages = { '!file:p': '\\V' . escape(expand('%:p'), '\\') }
```
Admittedly this is less than great compared to the single option we used to have, but it does solve the problem in general, and buzzword lovers would be able to call it "idiomatic". :)

**Comment by faceleg** [comment]
Thanks for the excellent and entertaining explanation, and for the code you wrote to support this new idiom.
