### ISSUE TITLE
NUL file for typescript

### ISSUE THREAD

**Issue by kirilloid** [scrooloose/syntastic#1296]
The same issue as existed (#963) now affects typescript files.

**Comment by lcd047** [comment]
Please see #1155.  It's a problem in Node.js, or more precisely in libuv.  All checkers based on Node.js are affected, not just tsc or lessc.  Syntastic won't add workarounds for all these checkers: if Node.js is happy to live with this, so is syntastic.  If you want to see it fixed, you'll have to get it fixed in libuv; sorry about that.
