### ISSUE TITLE
":SyntasticInfo" yields "Available checkers: - " for Haskell file

### ISSUE THREAD

**Issue by joyofdata** [scrooloose/syntastic#1309]
Hi!

I have a file test.hs with two syntactical mistakes:

```
f :: Bool > Int
f n = 
  | n = 1
  | n = 0
```

I would now assume those to be highlighted or snytastic showing me a message. But nothing whatsoever happens.

Output for `:SyntasticInfo`:

```
Syntastic version: 3.6.0-4
Info for filetype: haskell
Global mode: active
Filetype haskell is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

Haskell syntax checker files are available:

```
raffael@raffael-GT60 ~> ls -la .vim/bundle/syntastic/syntax_checkers/haskell/
total 24
drwxrwxr-x  2 raffael raffael 4096 Jan 28 19:45 ./
drwxrwxr-x 88 raffael raffael 4096 Jan 28 19:45 ../
-rw-rw-r--  1 raffael raffael 3033 Jan 28 19:45 ghc-mod.vim
-rw-rw-r--  1 raffael raffael 2004 Jan 28 19:45 hdevtools.vim
-rw-rw-r--  1 raffael raffael 1106 Jan 28 19:45 hlint.vim
-rw-rw-r--  1 raffael raffael 1367 Jan 28 19:45 scan.vim
```

Relevant section of my loaded `~/.vimrc` [(full .vimrc)](https://gist.github.com/joyofdata/df86b48e91491bfa9512) is:

```
...
Plugin 'scrooloose/syntastic'
 
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
 
let g:syntastic_haskell_checkers = ['hdevtools', 'hlint', 'ghc_mod']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
...
```

What am I doing wrong?

Thanks in advance

**Comment by lcd047** [comment]
This is answered in the [FAQ](https://github.com/scrooloose/syntastic#faqinfo): you need to install some third-party checkers.

> Haskell syntax checker files are available:

Nope, those files are the code in syntastic to parse the output of `ghc-mod`, `hdevtools`, `hlint`, and `scan`.  But `ghc-mod`, `hdevtools`, `hlint`, and `scan` aren't available, either because you don't have them installed, or because you don't have them in your `$PATH` (or for some other, more obscure reasons, but let's clear out these ones first).

**Comment by joyofdata** [comment]
Thanks

```
cabal update
cabal install hlint
[add ~/.cabal/bin to $PATH]
```
