### ISSUE TITLE
Bundled Swift syntax checker is dangerous and should be disabled immediately

### ISSUE THREAD

**Issue by kballard** [scrooloose/syntastic#1326]
The bundled Swift syntax checker is actually _really bad_ and should be immediately disabled. Specifically, it's not just checking the syntax of the file, it's actually _running_ the compiled program. And if the compiled program is going to do something bad when run without arguments, this is a _really bad idea_.

Since Swift is still such a moving target, I'd strongly advise removing the Swift syntax checker completely and letting the Swift vim ftplugins (such as [my own](https://github.com/kballard/vim-swift)) provide the Syntastic checker. Swift-specific plugins can be expected to keep up with any backwards-incompatible changes in the swiftc command-line options better than Syntastic can.

**Comment by lcd047** [comment]
> The bundled Swift syntax checker is actually _really bad_ and should be immediately disabled. 

We had similar problems with the `perl` and `elixir` checkers, so I suppose the same solution can be used here.  Done in 4782184; you can `g:syntastic_enable_swift_xcrun_checker` to 1 in your vimrc to re-enable the checker.

> Since Swift is still such a moving target, I'd strongly advise removing the Swift syntax checker completely and letting the Swift vim ftplugins (such as [my own](https://github.com/kballard/vim-swift)) provide the Syntastic checker. Swift-specific plugins can be expected to keep up with any backwards-incompatible changes in the swiftc command-line options better than Syntastic can.

Since you ask: while you're obviously in a better position than I am to follow Swift development (particularly so since I barely know what Swift is, in the first place :) ), I'd rather convince myself your checker actually works as intended before removing the one in syntastic.  No offence intended, but right now I'm having a bit of trouble doing that.  For one thing, `executable('xcrun swiftc')` is never going to return true. _shrug_

**Comment by kballard** [comment]
> I'd rather convince myself your checker actually works as intended before removing the one in syntastic. No offence intended, but right now I'm having a bit of trouble doing that. For one thing, `executable('xcrun swiftc')` is never going to return true.

That's why I define my own `SyntaxCheckers_swift_swiftc_IsAvailable()`. What it's doing is checking if the executable matches the default `xcrun swiftc` and uses a different approach to check if it's available. If the executable has been overridden by the user to be some other binary, then it falls back on `executable()`. So it won't be calling `executable('xcrun swiftc')`.

FWIW, I've been using my syntastic checker for the past 8 months. I'm pretty certain that it works.

**Comment by lcd047** [comment]
> That's why I define my own `SyntaxCheckers_swift_swiftc_IsAvailable()`. What it's doing is checking if the executable matches the default `xcrun swiftc`

What you're doing is, you're overloading things without bothering to check what they are supposed to do.  The `exec` variable is supposed to point to an executable, not to an executable with arguments.  There are other mechanisms to add arguments.  Your `s:getExec()` is also pretty awkward.  May I suggest you look at the checker in syntastic for a cleaner approach?

> and uses a different approach to check if it's available. If the executable has been overridden by the user to be some other binary, then it falls back on `executable()`.

So, if the user wants to run, say, `xcrun swift` instead of `xcrun swiftc`, how would that be done? :)

**Comment by lcd047** [comment]
By the way: if the user wants to run something _substantially_ different from `xcrun swiftc`, the preferred approach is to write a separate checker, rather than make the existing one handle both cases.

**Comment by kballard** [comment]
> What you're doing is, you're overloading things without bothering to check what they are supposed to do. The `exec` variable is supposed to point to an executable, not to an executable with arguments.

There is almost zero documentation on this stuff, last I checked. As best as I understand, what the `exec` variable does is threefold:

1. Provide the default `IsAvailable` test using `executable()`
2. Provide the value of `self.getExec()` in the checker
3. Provide a way for the user to override the value

Since I'm providing the `IsAvailable` test myself, is there any harm that can be caused by using a string like `'xcrun swiftc'` as the `exec`? Note that the compiler in this case is actually `swiftc`, and in fact on OS X 10.10 the compiler could just be listed as `swiftc` because OS X 10.10 provides a shim at `/usr/bin/swiftc` that does the equivalent of `xcrun swiftc`. The `xcrun` tool is part of the Xcode command-line tools that locates the given command inside of the installed Xcode developer dir. so `xcrun swiftc` is actually locating the tool `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc` and running that. Which is to say, conceptually, `xcrun swiftc` is the executable. It doesn't make sense to list `xcrun` as the executable, because that doesn't do anything on its own (and because it's always available on OS X even if Swift isn't). What might make more sense is listing `'swiftc'` as the `exec`, but still modifying it to use `xcrun swiftc` as the command to execute. And I'll probably make that change.

> Your `s:getExec()` is also pretty awkward.

My `s:getExec()` is awkward because my plugin supports a bunch of extra behavior (notably, support for selecting different Xcode installations to use). So it detects whether the `exec` value looks like `swiftc` or `xcrun swiftc`, and calls into my plugin code to do the extra work necessary to handle the selected developer dir. I could plausibly just ignore `self.getExec()` and unconditionally use my plugin code, but I prefer to not ignore the user's customizations.

> By the way: if the user wants to run something _substantially_ different from xcrun swiftc, the preferred approach is to write a separate checker, rather than make the existing one handle both cases.

Agreed. But perhaps the user has written a script that wraps `swiftc` and provides some custom behavior, and they want to use that script as the compiler? That's not substantially different, and I'd prefer my plugin to not completely ignore the user's override of the executable.

> So, if the user wants to run, say, `xcrun swift` instead of `xcrun swiftc`, how would that be done? :)

The user shouldn't be doing that. `swift` is a JIT interpreter, not a compiler, and I find it highly implausible that the user would want Syntastic to be actually running their script instead of merely parsing it. But if they really wanted it, they could override `exec` to `'xcrun'` and `exec_after` to `'swift'`.

**Comment by kballard** [comment]
FWIW, I just pushed the change that defines `'exec'` as `'swiftc'` instead.

**Comment by lcd047** [comment]
> There is almost zero documentation on this stuff, last I checked.

There is a [guide](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide).  It's far from complete, but I wouldn't call it "almost zero documentation".

> Since I'm providing the `IsAvailable` test myself, is there any harm that can be caused by using a string like `'xcrun swiftc'` as the `exec`?

Yes: `exec` is used internally in other ways, f.i. for versions.  It's a design assumption that if `exec` is used at all, it points to an actual executable.

> Note that the compiler in this case is actually `swiftc`, and in fact on OS X 10.10 the compiler could just be listed as `swiftc` because OS X 10.10 provides a shim at `/usr/bin/swiftc` that does the equivalent of `xcrun swiftc`.

Yes, nothing new here, other checkers work more or less the same way, f.i. `hdevtools`, `scalastyle`, the `r` checkers, `yamlxs`, HTML `validator`, and many others.  `exec` is the minimal thing users need to change to cope with packages installed in non-standard locations, multiple versions of the same checkers, and the like.  "Constant" arguments are not part of it.

> My `s:getExec()` is awkward because my plugin supports a bunch of extra behavior (notably, support for selecting different Xcode installations to use).

Your `s:getExec()` is awkward because you're trying to overload a standard accessor that also happens to be a dictionary function, and you can't make up your mind if doing that would break anything. :) So you end up with a sort of simulated overloading.  Don't do that. It does break things if you overload it, and you don't really need it to begin with.

> But if they really wanted it, they could override `exec` to `'xcrun'` and `exec_after` to `'swift'`.

Nope: the `*_before` and `*_after` are internal only, they can't be overridden by users.

> FWIW, I just pushed the change that defines `'exec'` as `'swiftc'` instead.

Much better already, but, as I said, `exec` should point to `xcrun`.  You can then set `exe` to `self.getExec() . ' swiftc'` or whatever you need to, and the user can both point syntastic to an `xcrun` in a non-standard location (assuming there is such a thing) by setting `exec`, and override `xcrun swiftc` by overriding `exe`.

Of course, `IsAvailable()` can do whatever you need it to do.

**Comment by kballard** [comment]
> There is a guide.

Huh, for some reason I thought the guide had a lot less info in it. And I often forget there even is a guide, since it's easy to skip past the link in the `:help syntastic` docs. My primary source has really just been the source code. But I should definitely give that guide a complete reading and see if there's anything important in there.

One suggestion would be to put a "Creating your own Syntax Checker" entry in the TOC of `:help syntastic` that contains a link to that guide. I generally look at the TOC of a plugin's docs and, if it doesn't contain anything relevant to my search, assume it's not in the documentation.

> Yes: `exec` is used internally in other ways, f.i. for versions. It's a design assumption that if `exec` is used at all, it points to an actual executable.

What do you mean by "for versions"? Also, according to the source, if `exec` is not present it defaults to the value of `name`, which means that even if I don't specify it at all, it will still be given a value (that may or may not correspond with an actual executable).

> `exec` is the minimal thing users need to change to cope with packages installed in non-standard locations, multiple versions of the same checkers, and the like. "Constant" arguments are not part of it.

I don't think you understand.

`xcrun` is not the Swift compiler. It's not required for the Swift compiler. It in fact has almost nothing at all to do with the Swift compiler. The only thing it does have in common with it is the Swift compiler is distributed as part of Apple's Xcode developer tools, and `xcrun` is a helper tool that locates and runs arbitrary commands that ship with Apple's Xcode developer tools. Just as `xcrun swiftc` runs the Swift compiler, `xcrun clang` will run `clang`, `xcrun ld` will run `ld`, etc. Some of these tools also have shims in `/usr/bin` that obviates the need for `xcrun`, but not all.

The way the bundled Swift syntax checker works, with having `exec` be 'xcrun'` and `args_after` be `swift`, is actually counterproductive. If the user wants to point to `swift` in a different location, overriding `exec` won't help, because it would then pass the completely useless string `'swift'` to the new binary. But beyond that, if the user wants to override the `args` value, then the syntax checker would completely break, because it would no longer even invoke the Swift compiler, instead it would attempt to invoke the user's arbitrary arguments as if they were an executable.

The only valid way to invoke `xcrun swift` using Syntastic is to pass `'xcrun swift'` as the value of the `'exe'` parameter.

> Your `s:getExec()` is awkward ... you don't really need it to begin with.

I wasn't trying to overload, I was just trying to avoid duplicated code between `IsAvailable` and `GetLocList`. But it ended up being more awkward than it was worth, which is why I removed it earlier today. Why do you say I don't need `getExec()` to begin with? If the user sets `g:syntastic_swift_swiftc_exec`, I want to respect their setting, and `self.getExec()` is the only way I know of to do that.

> Nope: the `*_before` and `*_after` are internal only, they can't be overridden by users.

I see. ~~How are they supposed to do that sort of thing (providing a multi-word command instead of a single executable) when overriding the executable for other syntax checkers? Since `'exec'` is escaped by default, there doesn't seem to be any way for the user to do this for arbitrary checkers. They can't assume that overriding `'args'` works because the checker might have defined an `'exec_after'` or an `'args_before'`.~~ Oh, users can actually override `exe` directly. I thought they had to override `exec`.

That said, there's no reason at all for users to want to set the executable to `xcrun swift`, so it's not something I particularly care about adding extra code to support.

> Much better already, but, as I said, `exec` should point to `xcrun`.

No, it really shouldn't. There is no such thing as `xcrun` in a non-standard location. And `xcrun` itself has nothing to do with Swift. The whole point of `xcrun` is to locate the tool that the user actually wants to run. If a user wants to point to `swiftc` in a non-standard location (though how they even _get_ `swiftc` in a non-standard location) then they should just override `exe`.

**Comment by lcd047** [comment]
> One suggestion would be to put a "Creating your own Syntax Checker" entry in the TOC of `:help syntastic` that contains a link to that guide.

It's [mentioned](https://github.com/scrooloose/syntastic/blob/47821840200cd8e14e99001caac602a37cdf8d5c/doc/syntastic.txt#L72-L75) in the first section of `:help syntastic`.

> What do you mean by "for versions"?

Some checkers need to run `stuff --version`.  Even if your checker doesn't need it, it's part of the API.

There's also `getExecEscaped()` which breaks if `exec` is not an executable.  It's also part of the standard API.  Even if your checker can get away with the wrong value, it breaks the API, which is almost guaranteed to break other things at some point.  Maybe some future functionality will break, or maybe some third party checkers decide they need the functions in your checker.  The point is you're breaking it, for no good reason.

> Also, according to the source, if `exec` is not present it defaults to the value of `name`, which means that even if I don't specify it at all, it will still be given a value (that may or may not correspond with an actual executable).

Some checkers (f.i. `vimlint`) don't need (or care about) `exec`.

If you don't specify `exec` it's copied from `name`, yes.  That's a syntactic shortcut,  with no real semantic meaning.  It saves people typing when they write checkers.  Whenever `name` doesn't correspond to an actual executable you'll notice there's also an explicit `exec`.

> I don't think you understand.

I think I do.  But we're already running in circles now, aren't we. :)

> `xcrun` is not the Swift compiler. It's not required for the Swift compiler.

As far as syntastic is concerned, it is required.  From syntastic's point of view, there's no difference between `xcrun swiftc` and `ghc-mod check`: the first parts (`xcrun` and `ghc-mod`) have to be executable, and the full incantations are required to run the corresponding checkers.  Syntastic really doesn't care that `xcrun` is just a helper and the real job is done by `swiftc`.

> Why do you say I don't need `getExec()` to begin with?

You don't need your version of it.  You could have defined a `dict` function named something else, and you would have had access to `self` for free.  Or you could have just just inlined the whole thing, since you only called it once. _shrug_

> There is no such thing as `xcrun` in a non-standard location. And `xcrun` itself has nothing to do with Swift.

Like I said: you're breaking the API.  Does the all layers in the API make logical sense for humans, for this particular checker?  Probably not.  Does it matter?  Probably not, as long as everything else keeps working.

**Comment by kballard** [comment]
> Some checkers need to run `stuff --version`.

`xcrun --version` would be entirely useless here. If you want to find the version of the swift compiler, `xcrun swiftc -version` is the right thing to execute.

> There's also `getExecEscaped()` which breaks if exec is not an executable. It's also part of the standard API. [...] The point is you're breaking it, for no good reason.

Since checkers can provide their own custom `exe` that doesn't use `exec`, or doesn't escape it, or does whatever else they want, I fail to see how the existence of `getExecEscaped()` is relevant. Nobody else should ever be calling that on an arbitrary syntax checker and expect it to do something useful for all checkers.

More generally, as near as I can tell, `exec` basically just provides some useful defaults that work for a lot of checkers. But it's not useful for all of them, which is why `exe` can be customized separately from `exec`, and why `IsAvailable` can be overridden.

> As far as syntastic is concerned, it is required. From syntastic's point of view, there's no difference between `xcrun swiftc` and `ghc-mod check` [...]

You still don't seem to understand. In the latter case, `ghc-mod` is the executable and `check` is a flag that tells it what mode to run in. So `ghc-mod check` seems roughly equivalent to `swiftc -parse`. `xcrun swiftc` is something entirely different. `xcrun` being present on the system *in no way* means that `xcrun swiftc` will do anything even remotely useful. The only valid reason to even look at `xcrun` directly is if you want to make sure you're running on OS X (which is something my whole plugin makes the implicit assumption is true, though the `IsAvailable` test of `system('xcrun -find swiftc')` should still properly decide that `swiftc` is not available if `xcrun` is missing).

In the `ghc-mod check` case, the presence of `ghc-mod` indicates that `ghc-mod` is available and therefore that `ghc-mod check` can be assumed to work. That's simply not true for `xcrun swiftc`.

> You could have defined a `dict` function named something else, and you would have had access to `self` for free. Or you could have just inlined the whole thing, since you only called it once.

I have seen nothing that leads me to believe that defining my own functions on the checker dictionary is a safe thing to do, so no, I'd still use a `s:` function instead of defining my own `dict` function. And I called it twice, not once.

> The point is, if done the way I described above, users can override `exec` and leave `exe` alone and the checker would still work`

Not with `exec='xcrun' args_after='swiftc'` it wouldn't.

> Like I said: you're breaking the API.

Am I breaking the API now, or are you still arguing from the perspective of `exec='xcrun swiftc'`? Because as I remarked in an earlier comment, yesterday afternoon I changed my syntax checker to remove the value for `exec` entirely (so it defaults to `swiftc`) and then if `exec == 'swiftc'` I override `'exe'` to be the correct `xcrun swiftc` invocation. And of course I'm still overriding `IsAvailable` so I can do the correct `xcrun -find swiftc` test. Since I'm testing for its value, users can still override `exec` to point to a different binary and the syntax checker will still work correctly. If they override `exe`, the `IsAvailable()` test will break, but again, AFAICT that's true of overriding `exe` without overriding `exec` for any syntax checker.

If anyone blindly assumes that they can look at the `exec` or `getExecEscaped()` value of my syntax checker and get something that they can invoke to run the compiler, they're mistaken (well, on OS X 10.10, `/usr/bin/swiftc` actually exists as a shim, but on 10.9 `xcrun` is required). But as near as I can tell, it's simply not correct to do that on arbitrary syntax checkers. If it was, there'd be no need for `IsAvailable` overrides or `exe` overrides.

**Comment by kballard** [comment]
After looking through the source, I found one more usage of `exec`, which is in the implementation of `g:SyntasticChecker.getVersion()`. It definitely is assuming that `self.getExecEscaped() . ' --version'` produces a string that can be evaluated to get the checker version. That seems rather wrong. I would imagine that there are a lot of checkers where that will break. And the only way to allow that API to work would seem to be to proactively call `setVersion` with the version (which would seem to be wasted work if nobody tries to fetch the version). Note that this isn't just wrong because `exec` might not be the right thing to execute here, but also because assuming all commands respond to `--version`, or print a parseable version when given that flag, is not reliable.

I'm surprised you don't have any way to provide a custom function that returns the checker version. That would seem to be the appropriate solution here.

**Comment by lcd047** [comment]
> Since checkers can provide their own custom `exe` that doesn't use `exec`, or doesn't escape it, or does whatever else they want, I fail to see how the existence of `getExecEscaped()` is relevant.

_sigh_ You're mixing checker author's perspective with user's perspective.

From checker author's perspective, `exec` is an attribute of the checker, `getExec()` and `getExecEscaped()` are accessors which produce results based on `exec`, and `exe` is a way to format the final command line also based on `exec`.

From user's perspective, overriding `exec` is a way to tell syntastic to look for the (external) checker in non-standard places and / or use a specific version, `exe` is something that is better left alone but can still be used for things like adding environment variables to the final command line, and `getExec()` and `getExecEscaped()` don't exist (they are dictionary functions, they aren't visible without a checker context).  If the user decides to mess with `exe`, she still has the mechanism of using brackets for escaping escaping.

> Nobody else should ever be calling that on an arbitrary syntax checker and expect it to do something useful for all checkers.

There is such a thing as one checker calling functions from another checker (`sh` calling `zsh`, JavaScript and Python checkers calling syntax highlighting functions from each other, results formatting, and so on).  Any checker _should_ call `getExecEscaped()` for another checker as needed.

> More generally, as near as I can tell, `exec` basically just provides some useful defaults that work for a lot of checkers. But it's not useful for all of them, which is why `exe` can be customized separately from `exec`, and why `IsAvailable` can be overridden.

`exec` is useful for _all_ checkers that run external programs.  It isn't useful for checkers that run internal Vim functions to do the checks (f.i. `vimlint`).  `exe` is a mechanism to build a command line based on `exec`, along with `args`, `args_after`, and the rest of their family.

`IsAvailable()` can be overridden because sometimes you need more checks to make sure a checker is available (f.i. ensure a minimal version).  But the most common situation is just `executable()`, so that's the default.

> You still don't seem to understand.

I believe this venue of discussion has over-lived its usefulness.  I made my point, you made yours.

> I have seen nothing that leads me to believe that defining my own functions on the checker dictionary is a safe thing to do, so no, I'd still use a `s:` function instead of defining my own `dict` function.

Defining your own dictionary functions in the context of a checker is safe (the checker doesn't know about them so it won't be calling them).  Overriding existing ones isn't.

> Not with `exec='xcrun' args_after='swiftc'` it wouldn't.

Which is why I said it should be `exec = 'xcrun'` and `exe = self.getExecEscaped() . ' swiftc'`.

> Am I breaking the API now, or are you still arguing from the perspective of `exec='xcrun swiftc'`? 

Still from the perspective of `exec='xcrun swiftc'`.  It's fine now (except for the `xcrun` stuff).

> I'm surprised you don't have any way to provide a custom function that returns the checker version.

Perhaps [look again](https://github.com/scrooloose/syntastic/blob/47821840200cd8e14e99001caac602a37cdf8d5c/plugin/syntastic/checker.vim#L82)?

**Comment by lcd047** [comment]
Ok, the included `xcrun` checker is gone: 471ce96.
