### ISSUE TITLE
Error messages from Ghc-Mod are displayed on one line

### ISSUE THREAD

**Issue by expipiplus1** [scrooloose/syntastic#1334]
With the (nonsense) Haskell file
``` Haskell
a
```

Syntastic reports 
```
a.hs|1 col 1 error| Parse error: naked expression at top levelPerhaps you intended to use TemplateHaskell
```

I'd expect the output from syntastic to be split over multiple lines as the output of `ghc-mod -b\n check a.hs` is:
```
a.hs|1 col 1 error| Parse error: naked expression at top level
  Perhaps you intended to use TemplateHaskell
```

System information:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 25 2014 03:23:11)
MS-Windows 64-bit console version
Included patches: 1-417
```
```
Syntastic version: 3.6.0-32 (Vim 704, Windows)
```
```
ghc-mod.exe version 5.3.0.1 compiled by GHC 7.8.4
```

**Comment by expipiplus1** [comment]
Passing `-b\n` to ghc-mod causes just the first line of the error message to be displayed

**Comment by lcd047** [comment]
> I'd expect the output from syntastic to be split over multiple lines

Not possible.  This is a limitation of the way Vim's `quickfix` works.

**Comment by expipiplus1** [comment]
I see.
In that case perhaps using a space as a separator rather than the empty string would be better.

**Comment by expipiplus1** [comment]
It's worth noting that ghcmod-vim's GhcModCheckAndLintAsync displays multi-line messages in the quickfix window. Is it possible because of differences in how quickfix and loclist work?

**Comment by lcd047** [comment]
> In that case perhaps using a space as a separator rather than the empty string would be better.

Passing `-b ''` is necessary because otherwise `ghc-mod` includes `NUL` characters in its output, and Vim's file reading functions can't cope with that.  Changing that to `-b ' '` wouldn't add anything useful, since continuation error lines already have at least one leading space.

> It's worth noting that ghcmod-vim's GhcModCheckAndLintAsync displays multi-line messages in the quickfix window.

It doesn't.  What ghcmod-vim shows [here](https://camo.githubusercontent.com/8878875698a96cb523bbbcc1d4f801238acb1895/687474703a2f2f63616368652e6779617a6f2e636f6d2f63303933393962326665333730636539643332386238656431323131386465382e706e67) are valid error lines intermixed with invalid ones.  You'll notice that going to, say, line 2 in the quickfix list and pressing `Enter` doesn't take you to the error line in the source.  Whether this is better than syntastic's UI or not is up to debate.  Syntastic can't cope with this kind of "fake" error lines, and there's no plan to change that.

> Is it possible because of differences in how quickfix and loclist work?

No.  The only difference between quickfix lists and loclists is that quickfix lists are global, while loclists are tied to their enclosing (Vim) window.
