### ISSUE TITLE
gcc: Disabling header checks not working?

### ISSUE THREAD

**Issue by ford-prefect** [scrooloose/syntastic#1345]
I don't really want syntastic to pop up errors related to missing includes on random C projects where I open files -- how do I suppress these errors by default? I tried the first three variables from https://github.com/scrooloose/syntastic/wiki/C%3A---gcc but they don't seem to help.

**Comment by lcd047** [comment]
Missing include files are fatal errors, you can't suppress them.  That is, you can tell syntastic not to show you these particular errors, but that would be less than useful, since gcc just stops parsing a file once it finds that an include file is missing.  This is how gcc works, nothing to do with syntastic.

**Comment by ford-prefect** [comment]
Is there a way to disable Syntastic for C and C++ only? I find that in practice, it doesn't really work for my use cases (lots of different include paths in projects, and I'd suggest gleaning that from Makefile/Makefile.am if I thought it was simpler).

**Comment by lcd047** [comment]
> Is there a way to disable Syntastic for C and C++ only?

Yes, set the `c` and `cpp` filetypes to passive, see `:help 'syntastic_mode_map'`.  Or set `g:syntastic_c_checkers` and `g:syntastic_cpp_checkers` to `[]`.

**Comment by ford-prefect** [comment]
Great, thank you!
