### ISSUE TITLE
`<html> proprietary attribute "class"` ?

### ISSUE THREAD

**Issue by MoOx** [scrooloose/syntastic#1350]
Not sure why I am getting this since it's not an error.

```html
<!DOCTYPE html>
<html lang="en" class="r-VerticalRhythm">
  <head>
    <meta charset="utf-8">
    <title>Test</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="dist/index.css" />
  </head>
  <body>
  </body>
</html>
```

**Comment by lcd047** [comment]
Please see the [FAQ](https://github.com/scrooloose/syntastic#faqhtml5).

**Comment by MoOx** [comment]
Maybe it's time to update the default linter for html that didn't receive any update since 2008 ?

**Comment by lcd047** [comment]
Sorry, but no.  This is a deliberate choice: defaults are changed only when there are strong reasons to do that.  This allows you to upgrade without worrying WTF you need to change in your vimrc today.

**Comment by MoOx** [comment]
HTML Tidy didn't get any update for 7 years + HTML5 is now an official w3c recommendation since several months (every browsers support it now). Not strong enough, seriously?

**Comment by lcd047** [comment]
Nope, the old tidy works as it's supposed to, and it's still widely available for most popular UNIX distributions.  tidy-html5 is still a relatively unknown project.  Your problem is not that either syntastic or tidy doesn't work; your problem is that tidy is a HTML4 checker.  Had you researched this properly, you would have found out about tidy-html5.  It's mentioned in the [wiki](https://github.com/scrooloose/syntastic/wiki/HTML%3A---tidy), and in the FAQ.

**Comment by MoOx** [comment]
Sorry for bothering you.

Note: IE5 also works as it's supposed to.

**Comment by lcd047** [comment]
> Note: IE5 also works as it's supposed to.

It does.  It's still up to you to decide if you want to use in 2015, and you're also responsible for the consequences of your decision. :)
