### ISSUE TITLE
How to configure vim syntastic for Maven project

### ISSUE THREAD

**Issue by sliter** [scrooloose/syntastic#1379]
I am trying to work on a Maven project using vim which has plugins such as NERDtree, syntastic, etc.

Here is the file structure:

my-app 
---|-- pom.xml 
---|-- src
--------|-- main
-------------|-- java
-------------|   -- com
-------------|       -- mycompany
-------------|           -- app
-------------|               -- App.java

The problem is that the vim shows nothing with "vi App.java" except I press "ctrl+c". Then, the vim gives back the normal text with syntastic disabled.

Here is my .vimrc:

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

If I:
- comment out the "let g:syntastic_check_on_open = 1", the problem will disappear
- change the name of the "pom.xml" to whatever(such as, 'pom', 'haha.xml'), the problem will disappear

Can anyone help me out of this issue? Thanks

**Comment by lcd047** [comment]
@troydm: Any comments?

**Comment by troydm** [comment]
@lcd047 I think he needs to run Syntastic check on this file atleast once manually for java syntax checker to initialize, I'm not quite sure what is wrong with his vim or why it's not working. Which vim version is he using? Does he have javac in his $PATH?

**Comment by sliter** [comment]
@troydm Thanks for you reply

$PATH
![1](https://cloud.githubusercontent.com/assets/3906050/7089051/97a6972a-dfcb-11e4-9903-9fe5a43cf6b0.PNG)

vim version
![2](https://cloud.githubusercontent.com/assets/3906050/7089054/a1518abe-dfcb-11e4-9432-ea8dc87e77f4.PNG)

What you mean by "run Syntastic check on this file atleast once manually for java syntax checker to initialize"?
I've opened the "App.java" without the "pom.xml" located under any of the listed folders, Syntastic works fine.

**Comment by troydm** [comment]
@sliter what happens why you execute :SyntasticCheck while having .java file opened?

**Comment by sliter** [comment]
@troydm Thanks for your reply

I think probably I am not well explained my problem at the beginning. With my config(let g:syntastic_check_on_open = 1), the :SyntasticCheck is enabled by default when I open a file.

The problem is:
When I open a .java file, I can't see the code and press any key is in vain.
![1](https://cloud.githubusercontent.com/assets/3906050/7092712/a447f60c-dfe6-11e4-8160-2972d8709fa1.PNG)

Then if I press "ctrl+c", then I can see the code
![2](https://cloud.githubusercontent.com/assets/3906050/7092715/a98c8c18-dfe6-11e4-8252-c8d92ab8a219.PNG)

If I continue to excute :SyntasticCheck, it will replay the problem.
![3](https://cloud.githubusercontent.com/assets/3906050/7092725/b3ccde30-dfe6-11e4-8d90-bce754719454.PNG)

If remove the "pom.xml" file or rename it to other names like "pom" or "haha.xml" and open the .java file again, it's ok.
![4](https://cloud.githubusercontent.com/assets/3906050/7092729/ba1c1526-dfe6-11e4-802d-04776955f50c.PNG)

**Comment by troydm** [comment]
@sliter do you have mvn in your $PATH? Have you tried disabling auto maven classpath loading
let g:syntastic_java_javac_autoload_maven_classpath = 0

**Comment by sliter** [comment]
@troydm 

> do you have mvn in your $PATH?
Yes, the mvn is included in the $PATH. Actually, I used the "apt-get install maven", so the mvn is under the /usr/bin.

> Have you tried disabling auto maven classpath loading 
> let g:syntastic_java_javac_autoload_maven_classpath = 0
I put this line in the .vimrc file. Now I can see the code when open the file. But it looks like that Syntastic does not work as expected. The Greeter.java is under the same folder and same package, but Syntastic does not recognize it.
![1](https://cloud.githubusercontent.com/assets/3906050/7100498/c8d019ac-e057-11e4-9aba-71f742f50dc3.PNG)

**Comment by troydm** [comment]
@sliter javac checker doesn't works the same way you imagine it does, also having maven support not working is kinda weird as the pom.xml is used for automatic classpath loading. Basicly for Greeter class to be recognized by javac checker you need it to be compiled atleast once so javac could reference it from target/classes folder however since you don't have automatic maven support working target/classes folder is not even included into classpath when javac is trying to compile your HelloWorld.java file. I suggest you try running manually "mvn dependency:build-classpath" and see if the command works.

**Comment by cula** [comment]
Hi all,
I meet with the exact same problem.
If 'let g:syntastic_java_javac_autoload_maven_classpath = 0', the problem is gone. 
But Syntastic will regard the dependencies defined in the pom.xml are not satisfied. So there will be many errors like "package junit.framework does not exist import junit.framework.Test"

@troydm 
Unfortunately, 'manually "mvn dependency:build-classpath"' does not work.

@sliter  
Do u find anything helpful to solve it?

**Comment by troydm** [comment]
@cula more details about operating system enviroment and what was the output of "mvn dependency:build-classpath"

**Comment by cula** [comment]
@troydm 
Thank u for your reply!
Now syntastic works after I reboot my virtual machine. (I use "mvn dependency:build-classpath"' first.)

I read some Syntastic code and guess that Syntastic maybe stuck in the first time of auto-running "mvn dependency:build-classpath"  with a new Maven because maven will download a lot of packages at the first time.  

Unfortunately,  Syntastic seems not to give out Maven's output. Meanwhile Vim is single-threaded, so it looks like Vim is dead with no output unless using "Ctrl+C" to stop Maven.

Manually  "mvn dependency:build-classpath"' is a good work-around of this problem.
Thank troydm again for the solution!

**Comment by troydm** [comment]
@cula sure, you are welcome
