### ISSUE TITLE
syntax error near unexpected token `(' when it's actually not a syntax error

### ISSUE THREAD

**Issue by welpo** [scrooloose/syntastic#1415]
The line:
IMAGES=(image.@(pn|jp?(e))g); ((${#IMAGES[@]})) && rm "${COVER[0]}"
Will be shown as having a syntax error:
syntax error near unexpected token `('
It's not actually a syntax error and bash will process it just fine.

In case it is necessary, my SyntasticInfo:
Syntastic version: 3.6.0-83 (Vim 704, Linux)
Info for filetype: sh
Global mode: active
Filetype sh is active
The current file will be checked automatically
Available checker: sh
Currently enabled checker: sh

**Comment by lcd047** [comment]
You do realise syntastic doesn't produce any syntax error itself, right?  Please try:
```sh
sh -n /path/to/your_script.sh
```

**Comment by welpo** [comment]
Maybe I should have been clearer:
> It's not actually a syntax error and bash will process it just fine.
The issue is that Syntastic will show it as a syntax error, but bash has no problem with that line.

**Comment by lcd047** [comment]
> Maybe I should have been clearer:

Maybe I should have been clearer too: please run the line above.  It's what the `sh` checker in syntastic runs to find out if your script has errors.

**Comment by welpo** [comment]
That does output the syntax error:
>syntax error near unexpected token `('

If I remove the second line of the script it will output the same error when trying to run it (normally). Second line being:
>shopt -s nullglob extglob

**Comment by lcd047** [comment]
This basically says `bash -n` doesn't take into account `shopt`s into the scripts it checks.  It has nothing to do with syntastic.  If you feel it's a bug, please report it to bash developers.

**Comment by cviner** [comment]
I obtain this same issue with `extglob`. I think that this ought be considered a regression in Syntastic:

While it is indeed the case, as @lcd047 notes, that Bash's dry-run (`bash -n`) does not correctly account for `shopt` options, `bash -n` was never intended to be a comprehensive syntax-checker, for linting—Syntastic is.

So instead of reporting this up-stream, might we be able to re-frame this issue as suggesting that a nice enhancement request to Syntastic would be to *extend* Bash syntax checking, beyond that provided by `bash -n`?

**Comment by lcd047** [comment]
@cviner Instead of pondering how to re-frame things I suggest spending a few minutes to understand what the current framework does to begin with. :smile: Syntastic was never intended to be a "comprehensive syntax-checker for linting".  What syntastic actually does is run third-party linters against your files, parse the output, and show it to you in a window.  Syntastic doesn't care about the contents of said files, much less about any languages or syntax.

If you want to improve the way syntastic works with `bash` files you'd have to either improve the already supported linters, or find new / better linters and [write syntastic checkers](https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide) for them.  That's all there is to it.

**Comment by cviner** [comment]
Well, fair enough! I would, however, consider the feature request to be precisely that.

I'm just saying that this seems like a valid and useful feature and a commonly-encountered annoyance in everyday use of Syntastic. I admittedly don't have to time to contribute to this and it sounds like you don't either—that's fine! But wouldn't this be a useful feature request (I never said this was a bug!) to keep open, so that those who might be able to improve this could be made more aware of this issue?
