### ISSUE TITLE
Feed Syntastic with Makefiles / CMake

### ISSUE THREAD

**Issue by Phyks** [scrooloose/syntastic#1431]
Hi,

I was wondering if there was any standard way to make Syntastic use compiler flags and include directories set in a CMakeLists.txt or a Makefile?

Sadly, I did not find much information on this subject.

Thanks!

**Comment by lcd047** [comment]
The short answer is "no".  The longer answer follows.

There are two levels of this problem.  First, syntastic can't really deal with checking several files at once.  There are a few workarounds, and a few particular cases where it can be done, but these are mainly exceptions.  This is a limitation of syntastic.  Vim can do it in principle: you have to set an `errorformat` and a `makeprg`, and run (Vim's command) `make`.  Syntastic used to do that too, but since Vim insists on expanding certain characters in filenames when running `make` (see `:help cmdline-special` if you're curious), it turns out it's impossible to quote filenames to survive both Vim and shell expansions.  So using `makeprg` was unmaintainable, and for this reason syntastic can now check only the current file (like I said, with a few notable exceptions).  This is mostly fine for things like JavaScript and Python, but not for C and C++.

The other layer is related to `make`, `cmake`, and the like: given a current file and a `Makefile`, a `CMakeLists.txt`, or whatever, there is no way to tell, with a reasonable effort, what flags are supposed to be used to compile the current file.  Some checkers (such as [clang_check](https://github.com/scrooloose/syntastic/wiki/C--%3A---clang_check)) can do away with that need, by using a [compilation database](http://clang.llvm.org/docs/JSONCompilationDatabase.html).  But that's a feature built into said checkers, not something syntastic can use at will.

Obviously, all this is a pain in the rear for projects that depend essentially on build systems.  Using config files is a tiny syntactic relief to it.  But I don't really see any better approach than what syntastic is doing now.  Of course, I'm open to suggestions.

**Comment by Phyks** [comment]
At the moment, the easiest way I found was to set a config file in my root directory with these options set. It works, but it means duplication of these information across the build files and the config file, and eventually versionning a config file which is useless for most of the people.

I agree that syntactic is perfect for Python or JavaScript :) For C / C++, it indeed requires a bit of tuning, but once done, it's really nice!

Being able to parse a makefile or cmakefile would be really nice to avoid duplication of information. As this may be a quite useful feature, I was wondering if I missed something in Syntactic or a complementary extension. I agree this problem is not easy. Other solutions I was offered were effectively building the config file on call, but this does not seem to be optimal either. I'll let you know if I have any better idea.

Thanks
