### ISSUE TITLE
For Haskell files working directories are not passed as includes to ghc

### ISSUE THREAD

**Issue by rjayatilleka** [scrooloose/syntastic#1462]
This is with all plugins but Vundle and Syntastic disabled. Syntax checking does not look for modules in the subdirectories of the current directory. I get errors like: `Could not find module ‘Foo’Use -v to see a list of the files searched for.` This is while Syntastic is running the `ghc-mod` and `hlint` checkers. If I run `let g:syntastic_haskell_checkers=['hlint']` to disable the ghc-mod checker, the error stops.

Presumably, the solution is to pass the flag `-isrc` to ghc-mod when its being called by syntastic. However, I have no idea how to do that. Note, the ghcmod-vim plugin has a way to pass arguments to ghc, but it doesn't need to, all the subdirectories of the current are included (or at least it works without any further configuration).

I'm running ghc 7.10.1 and an unreleased version of ghc-mod after the 5.2.1.2 release. I labeled it version 5.2.1.3, it's https://github.com/kazu-yamamoto/ghc-mod/tree/bfa0b965ee3497f5f41d261072dc6bae0af00a06.

```
Syntastic version: 3.6.0-111 (Vim 704, Darwin)
Info for filetype: haskell
Global mode: active
Filetype haskell is active
The current file will be checked automatically
Available checkers: ghc_mod hlint
Currently enabled checkers: ghc_mod hlint
```

To reproduce, use a project structured like this:

    project/
      src/
        Foo.hs
        Bar.hs

With files Foo.hs:

    module Foo where  
    
    foo :: String
    foo = "foo"

and Bar.hs:

    module Bar where

    import Foo 
    
    bar :: String
    bar = foo ++ "bar"

And launch vim from the `project` directory, NOT the `src` directory.

**Comment by lcd047** [comment]
> Presumably, the solution is to pass the flag `-isrc` to ghc-mod when its being called by syntastic. However, I have no idea how to do that.

Have you considered reading the [manual][man]?  Or perhaps the [FAQ][faq]?  Spoiler: it's called `g:syntastic_haskell_ghc_mod_args`.

> Note, the ghcmod-vim plugin has a way to pass arguments to ghc, but it doesn't need to, all the subdirectories of the current are included (or at least it works without any further configuration).

The `ghc_mod` checker in syntastic is a lot simpler than `ghcmod-vim`: it just runs `ghc-mod check --boundary="" /path/to/file.hs`.  Adding additional options to `ghc-mod` so that the checks actually make sense is entirely up to you.  Unless you can demonstrate a situation where `ghc-mod check` produces a set of errors when run in a terminal and a different set of errors when run from syntastic, this is a configuration problem not a bug.

[man]: https://github.com/scrooloose/syntastic/blob/8e672780e76c0a774b7fe834eed9652ccd684c24/doc/syntastic.txt#L708-L753
[faq]: https://github.com/scrooloose/syntastic#faqargs

**Comment by rjayatilleka** [comment]
I see. Thank you. I apologize for not doing proper research on how to implement the solution and wasting your time.
