### ISSUE TITLE
how to setup perl checker to run 'perl -cw' instead of 'perl -c'

### ISSUE THREAD

**Issue by qqibrow** [scrooloose/syntastic#1468]
Hi, how to setup perl checker to run 'perl -cw' instead of 'perl -c'? I tried `let g:syntastic_yaml_yamlxs_exec='perl\ -cw'` but it doesn't work.

**Comment by lcd047** [comment]
The `perl` checker already runs `perl -cw`.  The `yamlxs` checker doesn't need, nor supports, running under `perl -cw`.  So, what checker do you want to run, and what are you _actually_ trying to do?

**Comment by qqibrow** [comment]
maybe I misunderstood this page: https://github.com/scrooloose/syntastic/wiki/Perl:---perl but in this page, it mentioned it use `perl -c`. 

What I want is to detect syntax errors using `perl -cw`. However, when I check a file in which there are some errors by manually running `perl -cw`, no errors show up in syntastic.

**Comment by lcd047** [comment]
Syntastic first runs [`perl -c -X`](https://github.com/scrooloose/syntastic/blob/59513edd4784baf3d7350b91be7b739faddaf164/syntax_checkers/perl/perl.vim#L66), then [`perl -c -Mwarnings`](https://github.com/scrooloose/syntastic/blob/59513edd4784baf3d7350b91be7b739faddaf164/syntax_checkers/perl/perl.vim#L77).   This is lame, but the reason is that otherwise warnings could obscure errors.  The side effect however is that warnings are only shown if there are no errors.  Basically this is only intended as a quick guard against syntax errors.  Use the `perlcritic` checker if you want more useful diagnostics.

Either way, changing `g:syntastic_yaml_yamlxs_exec` is not going to have any effect on the `perl` checker.

**Comment by qqibrow** [comment]
But it doesn't show up any errors even missing braces. When I run `perl -cw` manually, it did show errors. Therefore, there is for sure some settings wrong but I cannot figure out.

```
Syntastic version: 3.6.0-117 (Vim 704, Linux)
Info for filetype: perl
Global mode: active
Filetype perl is active
The current file will be checked automatically
Available checkers: perl perlcritic podchecker
Currently enabled checker: perlcritic
```

**Comment by lcd047** [comment]
Please post a test file that illustrates the problem.

**Comment by qqibrow** [comment]
sure. sample code:
```
#!/usr/local/bin/perl -w
use strict;
use warnings;

my $good = 1;
$bad = 2; # no my specified as local variable.

while($good < 5
    $good += 1;
```
test result:
```
perlcritic test.pl
test.pl source OK

perl -cw test.pl
Scalar found where operator expected at test.pl line 9, near "$good"
        (Missing semicolon on previous line?)
Global symbol "$bad" requires explicit package name at test.pl line 6.
syntax error at test.pl line 9, near "$good "
test.pl had compilation errors.
```
no errors in syntastic.

**Comment by lcd047** [comment]
As I said: your `perl` checker is not enabled.  It seems to be working fine here:
![2015-07-09-205651_562x184](https://cloud.githubusercontent.com/assets/1281736/8602817/1a4c8cc8-267d-11e5-9179-28705f778b40.png)

**Comment by qqibrow** [comment]
How to set this? I tried `let g:syntastic_perl_interpreter='perl'` but it doesn't work.

**Comment by lcd047** [comment]
Just like any other checker, you also need to add it to `g:syntastic_perl_checkers`:
```vim
let g:syntastic_perl_checkers = ['perl', 'perlcritic']
```

**Comment by qqibrow** [comment]
yeah! after I set `let g:syntastic_enable_perl_checker = 1` and `let g:syntastic_perl_checkers = ['perl', 'perlcritic']` it works! Thank you your your help!
