### ISSUE TITLE
Location List height grows when switching to different panes

### ISSUE THREAD

**Issue by gblock0** [scrooloose/syntastic#1489]
When I move back and forth between two or more panes (some with errors detected by Syntastic and some without any) the top Location List height grows to become almost the full height of the window.

I've looked online and haven't found any way to resolve this.

Here are my Syntastic settings:
```
let g:syntastic_javascript_checkers = ['jshint', 'jscs']
let g:syntastic_html_checkers = ['']

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_loc_list_height=5
nnoremap <Leader>{ :lprev<CR>
nnoremap <Leader>} :lnext<CR>
```

VIM Version:
**VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2015 10:16:41)
MacOS X (unix) version
Included patches: 1-712
Compiled by Homebrew
Huge version with MacVim GUI.**

Syntastic Version:
**Syntastic version: 3.6.0-128 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
syntastic: error: checker output:
zsh:1: command not found: jsxhint
syntastic: error: checker javascript/jsxhint: can't parse version string (abnormal termination?)
Available checkers: jscs jshint
Currently enabled checkers: jshint jscs**

I'm not sure why Syntastic is looking for jsxhint when I haven't specified it in any of my files. Would this error cause the location list height to grow?

**Comment by lcd047** [comment]
There is no code in syntastic to resize windows.  There is exactly one place in the code where a window height is referenced, and that's the line that opens the error window:
```vim
execute 'lopen ' . syntastic#util#var('loc_list_height')
```
If you're seeing a window changing size this is either the doing of some other plugin, or you have stacked so many windows atop each other that `winheight`, `winminheight` (and whatever other traps Vim has set there for you) are kicking in.  Either way, it has nothing to do with syntastic. _shrug_

On a side note: if you want disable checks for `html` you could either set `html` as a passive filetype, or set `g:syntastic_html_checkers` to an empty list:
```vim
let g:syntastic_html_checkers = []
```

**Comment by gblock0** [comment]
Ok. Thanks for checking.

**Comment by expipiplus1** [comment]
@gblock0 did you ever find a solution to this?

**Comment by gblock0** [comment]
@expipiplus1 No :( I just don't show the location list by default now

**Comment by lcd047** [comment]
Does the problem go away if you disable all other plugins?  If it does, you can try disabling plugins in turn (something aking to binary search might help here), until you find the culprit.  If it doesn't, the problem is likely to be related to a setting in your vimrc.  Here again you might try to comment things out in turn (and some kind of binary search might help), but finding the problem is likely to be more complicated.

**Comment by expipiplus1** [comment]
@lcd047 As far as I can tell, the culprit is `autocmd FileType qf wincmd J` which makes the loclist always be at the bottom of the screen, so when a new one is opened, it bumps up the old one.

I've been tinkering with something like this, but my vimscript-fu is very poor. Note, this doesn't work because it enters a loop of always calling `lopen`, because when it's finished opening the new window vim enters the parent buffer, and calls the autocmd again!

```
function! OpenLocListPerhaps()                       
  let l:l = len(getloclist(0))
  if (l > 0 && 0)
    let l:s = min([l, 10])
    execute "lopen " . s
  endif
endfunction                                             

autocmd BufUnload,BufWinLeave,BufLeave *.hs,*.lhs,*.c,*.cpp lclose
autocmd BufEnter *.hs,*.lhs,*.c,*.cpp call OpenLocListPerhaps()
```

**Comment by lcd047** [comment]
Syntastic doesn't set `autocmd FileType qf`. _shrug_

**Comment by expipiplus1** [comment]
oh sorry, that was something from my vimrc
