### ISSUE TITLE
eslint checker does not engage automatically

### ISSUE THREAD

**Issue by matatk** [scrooloose/syntastic#1502]
I just did a clean install of syntastic (on vim 7.4.712) and would like to automatically check a javascript file.  When I have only eslint on the system, it is not enabled by default:

```
Syntastic version: 3.6.0-144 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: eslint
Currently enabled checkers: -
```

However, when I issue `:SyntasticCheck eslint` it does correctly run eslint and shows up several errors.  The errors are *not* shown when the file is first loaded, nor when I issue `:w`.

When I have jshint (only) installed, as soon as the .js file is opened I see the errors window pop-up.

I have got no `g:syntastic_*` variables set, except for the recommended configuration from your documentation.

If I have jshint (only) installed, I get this:

```
Syntastic version: 3.6.0-144 (Vim 704, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: jshint
Currently enabled checker: jshint
```

and, as mentioned above, the file is checked when it's first loaded, and on subsequent saves.

Happy to send some debugging information if necessary (though not exactly sure what you'd need).

**Comment by lcd047** [comment]
Please open Vim, run the following command, and read the very first paragraph: `:help syntastic-quickstart`.  Then read `:help syntastic-filetype-checkers`.

**Comment by matatk** [comment]
Thanks for the quick reply.  However I'm not sure that answers my question... I understand that there are default lists of checkers for given filetypes, and that these are kept minimal for performance reasons.  What I don't understand is, why does syntactic not use the only checker that it is aware of, given that checker is installed?

In my case, syntastic knows about both eslint and jshint -- it knows how to call them, and it knows when they are on the system.  But it will only use jshint automatically.  If I only have eslint, it knows it's there, but it won't use it.

This seems to me to be counter-productive 'out-of-the-box' behaviour.  Why not have syntastic activate eslint if it's the only checker on my system?

 * When I have tried editing other filetypes (such as HTML), it will both recognise and activate a checker on file load.
 * When I edit a JS file and have only jshint installed, it will activate the checker on file load.
 * When I edit a JS file and have only eslint installed, it will not activate the checker on file load (but it knows eslint is there).

Hope this helps clarify my question.  Please let me know if there's any debugging info I can provide to help track the cause of this apparently different behaviour for when eslint is installed.

**Comment by lcd047** [comment]
> This seems to me to be counter-productive 'out-of-the-box' behaviour.

Yup, you aren't supposed to run syntastic with the default configuration.  There is no one size fits all, it simply isn't possible to set defaults that are not harmful in some situations, let alone pick one that makes sense for most people.

> Why not have syntastic activate eslint if it's the only checker on my system?

Because syntastic doesn't check for the existence of _all_ checkers it knows of, it only checks for the existence of checkers in a predefined list.  Checking for `rubocop` on Mac OS-X used to take 5 seconds (!).  You don't want to wait for that if you don't care about `rubocop`.  It's much easier for you to tell syntastic which checkers you want to run.  You only have to do it once.

> Please let me know if there's any debugging info I can provide to help track the cause of this apparently different behaviour for when eslint is installed.

This is the expected behaviour: `jshint` is on the default list, `eslint` isn't.  You need to set the `g:syntastic_javascript_checkers` list, that's all there is to it.

**Comment by matatk** [comment]
Thanks; this makes a lot more sense.  The thing that caused my confusion is that, to the best of my knowledge, eslint *did* appear within syntastic without me doing anything (I hadn’t run it from the command-line or set up an .eslintrc when it was first automatically detected by syntastic, IIRC).  That left me in the position of thinking: syntactic knows it’s there by default, knows it’s the only one I have, but still doesn’t enable it by default.  (Sorry if I’m wrong about that; seems I could well be.)

Understood that people may have other checkers they want to use — and 5 seconds: wow.

I still think that a reasonable behaviour to have would be for syntastic to enable the only checker found, in the absence of a user-specified `g:syntastic_filetype_checkers` variable, though I certainly appreciate that, as users are discouraged from relying on the defaults, this is likely to be a low-priority feature request :-).  Understood if you want to close this.

Thanks again for your quick and comprehensive replies (and for your work on syntactic).

**Comment by lcd047** [comment]
> The thing that caused my confusion is that, to the best of my knowledge, eslint _did_ appear within syntastic without me doing anything

Actually, I was wrong, I remembered incorrectly what was going on.  `:SyntasticInfo` does probe for all checkers for the current filetype, that's where the "available" list comes from.  But this is way too slow to be done by default, especially for filetypes with many known checkers.  If you don't run `:SyntasticInfo`, only the checkers on the configured list (either the default, or the user-defined one) are probed.

> I still think that a reasonable behaviour to have would be for syntastic to enable the only checker found, in the absence of a user-specified `g:syntastic_filetype_checkers` variable

As I said: this is slow.  Actually, looking for existence of the known checkers is reasonably fast, but validating them (checking versions and the like) can be dead slow.  It would be possible in theory to improve the selection of the default checkers.  However, this would involve adding a "maybe available" state to some already hairy code, and running that way isn't even supposed to be supported.

The entire list of default checkers exists for only one reason: to show people which install syntastic for the first time that it actually _does something_.  It was an idea that proved to be way more trouble that its worth, not only because it complicates the startup for no reason, but also because it gives people hope that they can get away with the defaults. :)
