### ISSUE TITLE
ruby/mri raises new hashes warning

### ISSUE THREAD

**Issue by itsNikolay** [scrooloose/syntastic#1506]
ruby/mri raises errors for new string hashes
```
lib/xxx.rb|17 col 19 error| unexpected ':', expecting =>
```
for following:
```
{
 'a': 1
}
```

**Comment by lcd047** [comment]
Let's start with the beginning: what did you do, what did you expect to happen, and what happened instead?

**Comment by itsNikolay** [comment]
I have hash with dashilized key
<img width="339" alt="screenshot at aug 07 14-57-27" src="https://cloud.githubusercontent.com/assets/786577/9135322/b3950ae2-3d14-11e5-93e3-78c5c0be39f5.png">
but it raises validation error
<img width="638" alt="screenshot at aug 07 14-56-03" src="https://cloud.githubusercontent.com/assets/786577/9135325/c11e85bc-3d14-11e5-903d-cdb20bb723df.png">
ruby version: 2.2.2

**Comment by lcd047** [comment]
Syntastic doesn't rise any errors.  It doesn't care about the contents of your files.  What syntastic does is, it runs external checkers against your files, and shows you their output in a window.  It doesn't do anything smarter than that.  If you get an error in the error window it's because a checker produced it.

Now, in your particular case, the reason for the error is _likely_ to be that the version of ruby seen by syntastic doesn't match the one you get in a terminal.  You can check that by running something like this:
```vim
:echo syntastic#util#system('ruby --version')
```
You can also check the `$PATH` seen by syntastic:
```vim
:echo syntastic#util#system('echo $PATH')
```
In turn, if you happen to use `zsh` and `rvm`, a common cause for that problem is calling `rvm` from the wrong rc file.  See `:help syntastic-zsh`.

If all that doesn't help you'll have to enable debugging and post some logs.

**Comment by itsNikolay** [comment]
```
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/heroku/bin:/Users/itsnikolay/bin:/Users/itsnikolay/.gvm/bin:/Users/itsnikolay
/.nvm/versions/node/v0.12.7/bin:/usr/local/opt/rbenv/shims:/usr/local/opt/rbenv/bin:/home/itsnikolay/android/android-sdk-linux/tools
```
It seems like syntastic use native ruby verison (not rbenv current version)
Could you ask how to use zsh + rbenv ruby version?

**Comment by lcd047** [comment]
Try `:help syntastic-zsh`.  It's the same problem `rvm` has, hopefully it also has the same solution: move all `rbenv`-related incantaions from `.zshrc` to `.zshenv`.

**Comment by itsNikolay** [comment]
I've linked my `.zshrc` file to `.zshenv` now there's ruby version 2.2.2! thx!
