### ISSUE TITLE
Use -buildmode=archive by default, to speed up go build/test

### ISSUE THREAD

**Issue by gsalgado** [scrooloose/syntastic#1528]
According to the docs, this is what it does:

  Build the listed non-main packages into .a files. Packages named main are ignored.

However, it nevertheless compiles main packages, thus catching any errors in them.

Oh, and this would fix #1458 as well

**Comment by lcd047** [comment]
You can already set `g:syntastic_go_go_build_args` and / or `g:syntastic_go_go_test_args` to that. _shrug_

**Comment by gsalgado** [comment]
And that's what I'm doing. I posted as an issue because I think it'd make sense to use it by default so that people don't have to spend as much time as I did finding out those optimizations

**Comment by lcd047** [comment]
Ok, let's do it your way.  You break it, you get to fix it though. :) Commit 3c2e7e4.

**Comment by gsalgado** [comment]
Fair enough. Thanks for changing it so quickly, btw :)

**Comment by eriol** [comment]
I agree with @gsalgado about optimizations, but there is a huge problem in having this enabled by default because `-buildmode` was added only in Go 1.5 (see https://golang.org/doc/go1.5). So if you are not using Go 1.5, you will not be notified by errors anymore:
on go 1.4.x `go build -buildmode=archive` doesn't exist at all so you get usage message when you call it.

So it's not make sense to use this as default *for all go versions*, since the option does not exist in go < 1.5: can we version the use of -buildmode? It can be enabled only on go >= 1.5.

I reverted this change using `let g:syntastic_go_go_build_args = ""` in my vimrc, but to discover why after updating my plugins I lost syntastic error reporting only on go sources I had to bisect this repository. :smile:
Maybe the proper way to handle this, to not start handling different versions of go in the code, is to document possible optimizations.

I'm sure this speedup is very useful on Go 1.5, but we don't have to forget previous versions! :smile:

**Comment by gsalgado** [comment]
Oh, I hadn't realized -buildmode was a 1.5 addition. It should be possible to enable it only on go >= 1.5, but I'm not sure how to implement that. If @lcd047 can give me some pointers I'd be happy to give it a try

**Comment by lcd047** [comment]
Please upgrade to 3fb9865.  The commit adds a check for `go` version.  However, in the good `go` tradition, fixing something breaks something else: syntastic will no longer be able to use development versions of `go`.

On a side note: only official releases of checkers are supported anyway, but this is not enforced.  It just means I won't go out of my way to fix problems that exists only in development versions.  In this case however, the reason is simply that development versions of `go` don't return numeric versions `x.y`.  Refusing to work because of that seems ridiculous at best.  So, if any of you has a better approach, please step up.

**Comment by eriol** [comment]
@lcd047 many thanks for this quick fix!
It's unfortunate development versions of go don't return numeric versions, but one can alway override syntastic_go_go_build_args to make it work, no?

I think it is a feasible default now, maybe a note on the FAQ about using development version of Go with syntastic would be useful. What do you think?

I don't think there is a better approach, adding complexity to `syntastic#util#compareLexi` only to support development version of Go is not worth to me, the issue is clearly on golang side and is already reported here: https://github.com/golang/go/issues/11972

**Comment by lcd047** [comment]
> one can alway override syntastic_go_go_build_args to make it work, no?

Nope, the version detection has to succeed.

> I don't think there is a better approach, adding complexity to `syntastic#util#compareLexi` only to support development version of Go is not worth to me

Comparing commit IDs is pointless anyway.

**Comment by eriol** [comment]
> Nope, the version detection has to succeed.

Oh, thanks explaining and sorry, my knowledge of VimL is near to 0! :(

> Comparing commit IDs is pointless anyway.

Well, I was thinking not about comparing commit hash but to report this error condition (not being able to compare) and then handle this, for example for Go, don't passing `-buildmode`: the check will be slower but we can be sure it will occur.
But, as I said, I don't think adding this complexity is worth.
