### ISSUE TITLE
Error of opening another quickfix window

### ISSUE THREAD

**Issue by XadillaX** [scrooloose/syntastic#1538]
![pic](http://ww1.sinaimg.cn/large/a0d0b4c3jw1evsxu4wqgxj20n90l50u9.jpg)

When I save the file Syntastic start to work.

It not only open the error list window, but also open an empty quick fix window in area A. Why would it happen?

https://github.com/XadillaX/myvimrc/blob/master/.vimrc

This is my `.vimrc`. And even if I left only three plugins syntastic, nerdtree and minibufexpl, the quickfix still opened.

The quickfix window won't opened after I remove plugin minibufexpl.

But why would it happen?

**Comment by lcd047** [comment]
> It not only open the error list window, but also open an empty quick fix window in area A. Why would it happen?

It isn't a quickfix window, and it isn't opened by syntastic.  As far as I can tell, it's an unnamed buffer opened by minibufexpl.  As for why it happens, I'm afraid I don't understand the code in minibufexpl well enough to be able to tell, and I'd rather not spend too much time debugging somebody else's code.  Perhaps you could ask the author of minibufexpl?

In the mean time, I can only offer to add a note to the manual that syntastic is not compatible with minibufexpl.  Sorry about that.

**Comment by lcd047** [comment]
For what it's worth: the [original minibufexpl](http://www.vim.org/scripts/script.php?script_id=159) doesn't seem to have this problem.

**Comment by XadillaX** [comment]
The problem is:

my `.vimrc` works well in my old macbook. and i setup my new computer days ago and this problem appeared.

and `fholgado/minibufexpl`'s last update is 2 years ago but syntastic months ago.

**Comment by lcd047** [comment]
Like I said: the window is not opened by syntastic, and the problem doesn't happen with thje original minibufexpl. _shrug_

**Comment by XadillaX** [comment]
@lcd047 but the original one is too old. I mean it works ok in my old computer but not that good in my new one.

Since `fholgado/minibufexpl`'s last update was 2 years ago and syntastic updated months ago. is there any possibility that recently commits occurred this bug?

**Comment by lcd047** [comment]
The relevant difference between the original `minibufexpl` and the newer fork is the latter tries to do a lot more in `autocmd`s.  In particular, `minibufexpl` seems to get confused when syntastic calls its own `BufEnter`.  I'd speculate that the old versions used to work because of the way Vim handled `autocmd`s back then, rather than by design.  A lot of things have changed in Vim in that area in the last two years, and IMHO not all for the better.  I still maintain this is a bug in `minibufexpl`, and urge you to ask the current maintainer about it.  But if you believe something broke in syntastic recently, please feel free to run `git bisect` to find the commit responsible for the problem.

**Comment by XadillaX** [comment]
Hey @lcd047 , I found a previous version like a7fde99ea9a4eb26e6dfedb3ea54bbeefb71b325 works quite well with `minibufexpl`.

So I think that's some version between HEAD and a7fde99ea9a4eb26e6dfedb3ea54bbeefb71b325 made this issue.

**Comment by XadillaX** [comment]
@lcd047 finally I found the commit d26c7f78c124d90c9b26c88f6a908034e857118e that made this issue.

could you debug for it?

**Comment by lcd047** [comment]
Well, the bug is still in `minibufexpl`, it's just that the commit you point to exposes the problem.  Before said commit there was no conflict because syntastic's `autocmd`s didn't have the `nested` qualifier.  But the keyword is necessary for correct functioning of some checkers.

Now, can you please report the problem to the maintainer of `minibufexpl` and stop wasting my time with this?  Thank you!
