### ISSUE TITLE
Feature req: close location-list with q

### ISSUE THREAD

**Issue by laur89** [scrooloose/syntastic#1542]
Some plugins tend to follow this "standard" of closing newly opened windows with `q`.
Would be neat if that applied to the location-list opened with `:Errors`.

**Comment by lcd047** [comment]
Syntastic makes a point in __not__ messing with key definitions.  Also, you don't need to switch to the error window at all (cf. [FAQ](https://github.com/scrooloose/syntastic#faqlnext)).  But if you insist to do it, you can put something like this in a file `.vim/ftplugin/qf.vim`:
```vim
nnoremap <silent> <buffer> q :wincmd p<CR>:lclose<CR>
```
Better yet, you can run `SyntasticReset` instead of `lclose`, but this will break if you press `q` in a `loclist` window not opened by syntastic:
```vim
nnoremap <silent> <buffer> q :wincmd p<CR>:SyntasticReset<CR>
```
