### ISSUE TITLE
Cannot activate cpplint

### ISSUE THREAD

**Issue by MatthiasKauer** [scrooloose/syntastic#1569]
Hi,
I have used syntastic for a while with flake8 for Python and now I'd like to use it with C++ as well.
I have gotten running: vera++, g++ and cppcheck. Now I'm experimenting w/ cpplint.

I have installed it via pip and it works from command line.
```
sudo pip install cpplint
cpplint main.cpp
main.cpp:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
<more hints>
```

Other issues have talked about interference from other plugins so I have created a clean .vim folder with the following small vimrc and plug.vim in autoload.
```
let path='~/.vim/junegunn-plugs'
call plug#begin(path)
Plug 'scrooloose/syntastic'
call plug#end()
```
I then install syntastic via PlugInstall. ```git show``` reveals that I'm on 7e26d3589ab414155dff2c362a07e9e8bb970823.
Before updating my main vim config folder, I was probably on a build from a couple of weeks ago that behaved identically as far as I can remember now.

Syntastic Info (on main.cpp) reveals the following:
```
Syntastic version: 3.6.0-178 (Vim 704, Linux)
Info for filetype: cpp
Global mode: active
Filetype cpp is active
The current file will be checked automatically
Available checkers: cppcheck gcc verapp
Currently enabled checker: gcc
```

In other words, cpplint is not available.

In https://github.com/scrooloose/syntastic/issues/1488 you a command
```
:echo system('cpplint.py --verbose=3 myfile.cpp')
```
was suggested. Using it with 'cpplint' (removing .py) succeeds on my system. Otherwise, it returns cpplint.py not found.

I have subsequently downloaded the cpplint.py file on my own and made it executable + accessible in the PATH. Now, cpplint is listed in ```SyntasticInfo```
However, running ```SyntasticCheck cpplint``` doesn't seem to do anything.

Ok, after adding another line I found in issue 1488 referenced above
```
let g:syntastic_cpp_cpplint_exe = 'cpplint'
```
it appears to work as expected now. (I adjusted to cpplint from python cpplint.py).

I somehow had expected this would be the default, but I guess this solves the issue.

Kind regards,
Matthias

**Comment by lcd047** [comment]
Spending a few minutes to understand what you're doing instead of trying random things would have saved you a lot of time.  You probably want to use [`exec`](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#isavailablecallback) instead of [`exe`](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#makeprgbuildoptions):
```vim
let g:syntastic_cpp_cpplint_exec = 'cpplint'
```

**Comment by MatthiasKauer** [comment]
Hi. Your reply left me with more confusion than I had previously.
I decided to report after making it work on my end because I sort of expected cpplint to work out of the box after ```pip install cpplint``` just like flake8 did for Python. The [cpplint wiki](https://github.com/scrooloose/syntastic/wiki/C--:---cpplint) doesn't say anything about path adjustments being necessary.

Your comment about exe/ecec also confused me because in https://github.com/scrooloose/syntastic/issues/1488 you said the opposite (use exe, not exec). And it worked with exe on my end.

I'm sorry if I'm really just ignorant here.

**Comment by lcd047** [comment]
> I sort of expected cpplint to work out of the box after `pip install cpplint` just like flake8 did for Python.

At the time the checker was added `cpplint` couldn't be installed with `pip`.  The script that came with the `cpplint` package was named `cpplint.py`, so that's what syntastic looks for by to this day.

> The [cpplint wiki](https://github.com/scrooloose/syntastic/wiki/C++:---cpplint) doesn't say anything about path adjustments being necessary.

It does now.

> Your comment about exe/ecec also confused me because in #1488 you said the opposite (use exe, not exec).

That's because the problem there was path resolution for Python scripts on Windows for a particular Python distribution, rather than the script name not being different from what syntastic expects.  The standard way of dealing with your problem is to use `exec`, even though in your case setting `exe` appears to do the same thing.  The `exec` way works on all systems, and that's what the manual tells you to do.  Setting `exe` only works in some very specific situations.  And setting `exec` wouldn't have worked for #1488.
