### ISSUE TITLE
Syntastic crashes vim7.4 on Windows 7

### ISSUE THREAD

**Issue by drobati** [scrooloose/syntastic#1572]
http://i.imgur.com/j1eIXCa.png

I don't know how to copy `:version`. :frowning: 

Crashes vim when using python. I believe I have pylint installed.

Let me know if there is any way to debug, as I'll get you whatever information you need.

I know it's syntastic to the extent that when I disabled just that plug-in it stopped crashing.

**Comment by lcd047** [comment]
You're using an old (and particularly buggy) version of Vim, there have been ~900 patches released since 7.4.  Upgrade to a more recent version and try again.

If that doesn't solve the problem, please open a Python file, run `:SyntasticInfo`, and post the output.  It's unlikely that syntastic is the actual cause of a segfault (but it could trigger a bug elsewhere).

**Comment by vantreeseba** [comment]
@drobati Here is a set of downloads that are usually up to date
http://wyw.dcweb.cn/#download

You can also get the vim cream, or there are others.

**Comment by drobati** [comment]
@lcd047 Yeah, I'm not blaming syntastic. Just don't know how to debug the problem, and syntastic disabled stops the crash. I'll update Vim on windows and see if it fixes the problem.

**Comment by lcd047** [comment]
If you're serious about debugging this get a recent version of Vim, compile it with debugging information, run Vim under a debugger, and trigger the crash.  That's how it's done, there is no magic bullet.
