### ISSUE TITLE
Highlight CursorLineNr instead of signs

### ISSUE THREAD

**Issue by llfm** [scrooloose/syntastic#1583]
This is possible? How can I do it?
The more viable information I could find was this [#472](https://github.com/scrooloose/syntastic/pull/472)

* Signs is intrusive for me, because it's always changing the layout (creating that sidebar).

**Comment by lcd047** [comment]
It's possible to do it "together with", not "instead of".  You can tell syntastic to highlight the lines along with the signs (see `:help syntastic-error-signs`), but disabling signs will also disable this kind of highlighting.  It's a feature of Vim signs, not implemented by syntastic.  This is different from error highlighting (see `:help syntastic-highlighting`), which _is_ implemented by syntastic, and is quite another kind of animal under the hood.

**Comment by llfm** [comment]
Oh, thanks. I missed the vim signs lol.
