### ISSUE TITLE
Errors showing up in :Errors and quickfix list, but not in the gutter

### ISSUE THREAD

**Issue by scottopell** [scrooloose/syntastic#1584]
I'm working on a vim plugin for an XText dsl called statemachine (found here: https://github.com/scottopell/vim-statemachine) and I was able to hook up everything with syntastic, except when I save (to trigger SyntasticMake), I don't get lines highlighted with error/warning markers.

I do see the errors expected in `:Errors` and with `let g:syntastic_debug=3` I see this:

```
syntastic: 57.931112: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 57.931854: UpdateErrors: default checkers
syntastic: 57.932568: CacheErrors: default checkers
syntastic: 57.933724: g:syntastic_aggregate_errors = 0
syntastic: 57.933929: getcwd() = '/Users/scott/code/FOA/vim-statemachine'
syntastic: 57.942862: CacheErrors: Invoking checker: statemachine/statemachine
syntastic: 57.944013: SyntasticMake: called with options: {'errorformat': '%l: %m', 'makeprg': './validator.rb example_simple.sm'}
syntastic: 58.516673: checker output: ['4: extraneous input ''state'' expecting RULE_ID', '']
syntastic: 58.517720: raw loclist: [{'lnum': 4, 'bufnr': 0, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'extraneous input ''state'' expecting RULE_ID'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vc
ol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 58.518226: getLocList: checker statemachine/statemachine returned 0
syntastic: 58.518452: statemachine/statemachine raw: [{'lnum': 4, 'bufnr': 0, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'extraneous input ''state'' expecting RULE_ID'}, {'lnum': 0, 'bufnr': 0, 'col':
0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 58.518921: quiet_messages filter: {}
syntastic: 58.519896: aggregated: {'_sorted': 0, '_name': 'statemachine (statemachine)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 4, 'bufnr': 0, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text':
'extraneous input ''state'' expecting RULE_ID'}]}
```

Here's the output I get after `set verbose=15`: https://gist.github.com/scottopell/d9335975439e61171030

I have a very basic errorformat, which just sets line number and method. Do I need to set whether or not it's an error/warning before it will show up in the gutter?

**Comment by lcd047** [comment]
There are many problems with your plugin, but you didn't ask about that.  To answer what you did ask about: I think you need filenames for signs to work.

**Comment by scottopell** [comment]
lcd047: thanks, I'll give that a shot.

if you don't mind elaborating, what other problems did you notice? I'd like to make it as correct/idiomatic as possible.

**Comment by lcd047** [comment]
A few things about the syntastic checker:

* You override the `exe` in `makeprgBuild`.  This doesn't do what you think it does, although it works for now.  You should have used `exec` instead.
* You search for `validator.rb` at each check.  This doesn't make sense, since the script doesn't move between checks.  You could have used the `IsAvailable()` function to cache it.
* Your IsAvailable()` function always returns 1, but you make no attempt to check that `validator.rb`  actually works, and that all prerequisites (f.i. `curl`) are available.
* You didn't follow the instructions in the [guide](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#external) to set a `g:syntastic_extra_filetypes`.

Outside the checker, you also define a `compiler` for your `statemachine`.  This is not incompatible to syntastic, but it can be confusing.  Vim `compiler`s run `make` and produce `quickfix` lists.  Syntastic doesn't run `make`, and produces `loclist`s.  They look the same and behave (almost) the same, but they are definitely not the same.  Perhaps give up trying to write a syntastic checker if a simple `compiler` works for you?

There are other details, such as `statemachine#GetExePath()` searching upwards from the _current_ directory, which is probably not what you want.  There's more, but not things that can be explained in a GitHub post.  You'll hopefully discover them yourself at some point. _shrug_

**Comment by scottopell** [comment]
I'll add these to my todo list of things to fix up. A few of these things (such as `IsAvailable()` always returning )1 are temporary things until I can revisit them, but a few of those I definitely didn't know.

Thanks for taking a look!
