### ISSUE TITLE
Document default setting of checkers

### ISSUE THREAD

**Issue by blueyed** [scrooloose/syntastic#1607]
The list is in plugin/syntastic/registry.vim, but should be documented, possibly with a vim-help link target for the setting name (e.g. `g:syntastic_python_checkers`).

This could be automatically be built from the registry file maybe - or needs to be kept in sync manually.

(It should be noted of course that only available/existing entries from this list can be used.)

**Comment by lcd047** [comment]
The list of defaults is undocumented because you're not supposed to rely on it.  It's there for two reasons: to show first time users that syntastic _does something_, and to speed up filetype completion.  You're supposed to set a `syntastic_<filetype>_checkers` explicitly for all filetypes you use.

The problem with having defaults in the first place is that no list of checkers can ever be reasonable for all users.  People will argue that some checkers are better than others, while other people will argue that the same checkers are too slow to be run on every write.  People will argue about the order checkers are run, and they'll feel frustrated that some checkers are detected automatically while others aren't. Other people will argue that some checkers are incompatible to one another, and that trying to detect all checkers every time syntastic is run is stupid.  Yet other people will argue that if only one checker is installed, it should be used by default.  And so on, and so forth.  People love [bikeshedding](https://en.wikipedia.org/wiki/Parkinson's_law_of_triviality), and they'll go to great length to make sure change defaults are set their way.  This did happen here in the past, although, thankfully, not recently: I removed a checker from syntastic because a particularly toxic person wouldn't accept that defaults are there to be overridden as needed.

Of course, having "hidden" defaults has backfired too.  People see that syntastic mostly works without any `syntastic_<filetype>_checkers`, conclude their configuration is fine, and never give it another thought until they install a checker that isn't among the defaults.  Heck, you have posted this, and you're not exactly new to syntastic.

At some point I should probably remove these defaults completely, and simplify the startup code.  Then people will complain about syntastic being hard to set up. :)
