### ISSUE TITLE
Bug in g:syntastic_check_on_wq

### ISSUE THREAD

**Issue by Chronial** [scrooloose/syntastic#1622]
If `check_on_wq` is set, syntastic will "randomly" set `b:syntastic_skip_checks` on buffers. The problem is here:
https://github.com/scrooloose/syntastic/blob/70c723ac16fee7b4093d3d16a90544d877dea89e/plugin/syntastic.vim#L302

If I have multiple windows (eg. after `:split`) and I close one of them, `b:syntastic_skip_checks` will now be set on this buffer and if I later open it in another window, syntastic will just silently not run on this file anymore.

**Comment by lcd047** [comment]
The problem with your analysis is that the line you mention is called only from a `QuitPre` autocommand, which is supposed to run only right before Vim exits.  If it runs at any other moment (f.i. when you close a window), that's a bug in Vim, not in syntastic.

That said, the problem has been reported before (cf. #1603).  Please set `g:syntastic_debug` to 8 in your `vimrc`, and use Vim normally until you run into the problem.  Then run `:mes` and post the output.  This should be fine, because debug level 8 doesn't produce a huge amount of logs.

**Comment by Chronial** [comment]
Vim help disagrees:
> **QuitPre:** When using `:quit`, `:wq` or `:qall`, before deciding whether it closes the current window
or quits Vim.  Can be used to close any non-essential window if the current window is the last ordinary window.

I guess you meant to use `VimLeavePre`?

**Comment by lcd047** [comment]
Right, I was confused, sorry about that.  Please try 77e20e2.

**Comment by Chronial** [comment]
That looks like it fixed it. Thanks :).
