### ISSUE TITLE
No indicators coming from es6 linter

### ISSUE THREAD

**Issue by togakangaroo** [scrooloose/syntastic#1626]
[I cross posted this on Stack Overflow but](http://stackoverflow.com/questions/34081656/why-cant-i-see-any-indicators-from-syntastic) they suggested asking here. I'm not sure if this is an issue or if I just haven't finished configuring things.

I'm trying to use vim for my project. In order to do that I would like to get real-time feedback from eslint (like I get in sublime with [SublimeLinter-eslint](https://github.com/roadhump/SublimeLinter-eslint)) and am therefore trying to get [Syntastic](https://github.com/scrooloose/syntastic) working.

Everything seems to be set up properly but I'm not getting any indicators. Am I missing something? `:SyntasticInfo` seems to show the correct expected output but clearly I should be getting some sort of error on line 66 in this screenshot.

![eslint is enabled but not validating](http://content.screencast.com/users/togakangaroo/folders/Jing/media/99fba2a4-8558-4639-bc2b-3dad12976ee2/2015-12-03_2333.png)

**Comment by lcd047** [comment]
Syntastic doesn't work on the fly, it only runs checks when you save the file, and when you call it explicitly.

**Comment by togakangaroo** [comment]
How do you call it explicitly?

**Comment by lcd047** [comment]
`:SyntasticCheck`

**Comment by togakangaroo** [comment]
Hmm...here is a little screencast of me making some obvious errors, running that command and ... nothing. The screen blinks but that's it. What should I be expecting?

**Comment by lcd047** [comment]
Apparently the screencast got lost in translation. :) Did you save the file before running `:SyntasticCheck`?  Syntastic checks only files on disk.

**Comment by togakangaroo** [comment]
Huh...here is the link to the screencast http://screencast.com/t/4sfTc4Gj

**Comment by lcd047** [comment]
Please set `g:syntastic_debug` to 3, run the checker, then run `:mes`, and post the output.

**Comment by togakangaroo** [comment]
ah! That was helpful! So I needed to install eslint-plugin-react and eslint-plugin-mocha globally. I had them installed locally but that wasn't good enough.

Which begs the question - should syntastic just use the ones that are in this folder structure's node_modules? Again, that's what SublimeLinter does and fewer global dependencies seems like it would be better?

**Comment by lcd047** [comment]
You should install whatever ESLint needs to run when called from Vim.  Syntastic doesn't care either way (it just runs ESLint and shows you the results), but the interaction between Vim and node is, err, interesting.

As for how all that compares to SublimeLinter, well, Vim is some ~15 years older than Sublime Text, based on design that's 40 years old.  You should be surprised at what you can still do with it, rather than at what you can't. :)

**Comment by togakangaroo** [comment]
@lcd047 well of course but that sounds dangerously like a suggestion that you shouldn't use vim :) My question is whether I should open this up as a feature request. It might be as simple as just running the eslint shell script from the correct working directory.

**Comment by lcd047** [comment]
> well of course but that sounds dangerously like a suggestion that you shouldn't use vim :)

It is a suggestion not to use Vim. :) If you haven't used Vim for longer than you care to remember, and if you don't have any specific reason to use it, chances are you'll find other editors better suited to your needs these days.  Disclaimer: I've been using Vi for 30 years, and Vim almost since the beginning of the project.

> My question is whether I should open this up as a feature request.

Sorry, but no.  Syntastic tries hard to provide an abstract framework for all checkers.  From this point of view, checker-specific quirks are to be avoided.

You can add an `autocmd` to point `g:syntastic_javascript_eslint_exec` to a project-specific script.

**Comment by lcd047** [comment]
Please add a description to the checker options in the wiki for [r/lintr](https://github.com/scrooloose/syntastic/wiki/R%3A---lintr) and [rmd/lintr](https://github.com/scrooloose/syntastic/wiki/R---Markdown%3A---lintr).
