### ISSUE TITLE
Jump to line in location list from error in file?

### ISSUE THREAD

**Issue by phiche** [scrooloose/syntastic#1640]
I have a long file with 500+ lint errors that I'm slowly working through. I'm new to Syntastic, so I hope there is a solution to my problem already. I'm also using vim-unimpaired to assist with navigation between errors.

My workflow is as follows:
* run :SyntasticCheck (g:syntastic_always_populate_loc_list = 1)
* go through a few errors and fix them and skip over a few errors than i'll ignore or fix later
* :w to save a rerun :SyntasticCheck

But now I hit a problem because the loc_list always displays from the first error and I want error :12 or where ever I previously left off, but when I navigate to that error in the loc_list and hit <CR> I jump to where I was in the file, but the loc_list refreshes back up to the top of the list again. Is there configuration to stop this from happening?

I can use :lnext which takes me to the next error and the loc_list moves to the correct location, but since I've modified the files the error in the list is always approximate so I always have to find the precise line again.

What would be really nice if there was a way to jump to the line in the loc_list from the error in the file.
I discovered a question on stack overflow and another plugin that appears to do this:
http://stackoverflow.com/questions/14778612/jump-to-the-errors-in-the-quickfix-or-location-list-for-the-current-line-in-vim
https://github.com/vim-scripts/QuickFixCurrentNumber

But the question is more than 2 years so so I wanted to check if there native way to do this in Syntastic?

**Comment by lcd047** [comment]
> when I navigate to that error in the loc_list and hit I jump to where I was in the file, but the loc_list refreshes back up to the top of the list again. Is there configuration to stop this from happening?

Navigation through the loclist is handled by Vim, not by syntastic.  `:lnext` (or `]l`, since you're using unimpaired) is probably your best bet, and avoiding it doesn't achieve any useful purpose.

> I can use :lnext which takes me to the next error and the loc_list moves to the correct location, but since I've modified the files the error in the list is always approximate so I always have to find the precise line again.

Yes, loclists go out of synch as soon as you edit the buffer.  This is a limitation of using loclists to keep track of error locations, and there isn't much you can do about it (except switch to a more modern editor).  There is no good answer to this, but you can do a few things to alleviate the problem:

* turn off `syntastic_auto_jump`, if you have it set
* turn off useless error messages, by tuning the checkers' options and / or by using `syntastic_quiet_messages`
* run `:SyntasticCheck` often
* go through the error list upwards (using `:lprevious` or `[l`), to minimise the effect of your edits to the location of errors not yet visited.

> https://github.com/vim-scripts/QuickFixCurrentNumber

This plugin was written specifically to address the problem you mention, and its author is quite knowledgeable about Vim.  It probably still works with syntastic, I can't think of any reason for it to stop working, but I haven't actually used it.  The main limitation I can see from a quick look is that loclists are not always sorted, and if there are several errors referring to the same place in the file the plugin will always choose the first one (for some definition of "first").  I don't think it can possibly do better with the information available to it.

> I wanted to check if there native way to do this in Syntastic?

There isn't.  As I said, navigation through the loclist is outside the scope of syntastic.  And the plugin you mention above seems to do the best you can hope for.

**Comment by phiche** [comment]
Thanks for the feedback! 

It's good to know where the limitations really are and I can put my hope in neovim to solve them!

**Comment by zanona** [comment]
I am not sure if I am doing something wrong, but even where there are syntax errors in the file returned from syntastic, when using `:lnext`  or `:lprev` vim displays `E42: No errors` which is strange?

Perhaps I need to configure something else?

**Comment by lcd047** [comment]
@zanona Please read `:h 'syntastic_always_populate_loc_list'`.  If that doesn't address your problem, please open a __new__ issue, explaining what you did, what did you expect to happen, and what happened instead.

**Comment by zanona** [comment]
Thank you, it works now!
I have also found references to it from another issues and could use it with `:lfirst` as you have suggested previously.

**Comment by symbolix** [comment]
@zanona Hello, I am also trying to improve the link between syntastic and my own VIM config. I am curious to hear about what the complete solution is to the problem you are facing. Thanks.

**Comment by lcd047** [comment]
@symbolix The complete solution is to read the manual, and act accordingly.

**Comment by symbolix** [comment]
Thanks. Did you end up using the `QuickFixCurrentNumber` vim plugin?

**Comment by zanona** [comment]
@symbolix I have added the `let g:syntastic_always_populate_loc_list = 1` declaration to my `.vimrc` file, however since morning, vim has crashes several times since I started using it which is really unusual since it has never happened that often. I have disabled this options for now so I could work without problems for today. Not sure why this is happening.

**Comment by lcd047** [comment]
@zanona Please compile Vim with debug information, make it crash, and post the stack trace to vim_dev.

**Comment by niftylettuce** [comment]
I added `let g:syntastic_always_populate_loc_list = 1` and it fixed the issue for me (previously `ll`, `lprev`, and `lnext` were reporting `No Errors`)

**Comment by themadsens** [comment]
See my answer [on stackoverflow](https://stackoverflow.com/a/46754255/3697584)
