### ISSUE TITLE
Update JSXhint guidelines to point towards ESHint

### ISSUE THREAD

**Issue by phantomwhale** [scrooloose/syntastic#1651]
I am just setting up vim for Javascript development, whilst also trying to learn JSX / React. 

I stumbled across https://github.com/scrooloose/syntastic/wiki/JavaScript:---jsxhint - which sent me off to look into the JSXhint vim plugin - which THEN sent me off to install EShint via NPM and set that up inside of Syntastic.

Is this the recommended way to set linting up for React / JSX projects going forward ? In either case, might it be worth removing this page or adjusting it to recommend EShint as well ?

**Comment by lcd047** [comment]
> sent me off to look into the JSXhint vim plugin

I'm pretty sure the JSXhint the wiki sends you to is a node.js module, rather than a Vim plugin.

> Is this the recommended way to set linting up for React / JSX projects going forward ?

Why are you looking at syntastic for best practice guidelines about React / JSX?  Syntastic is a plugin for an editor.  It tries hard to be agnostic about the external checkers it uses.  It won't tell you how to deal with your projects.  The _recommended_ way to do things is to choose your tools first, then see if your editor (and in this case syntastic) can make your life easier.  Not the other way around. :)

> In either case, might it be worth removing this page or adjusting it to recommend EShint as well ?

It's code that (still) works.  It requires no maintenance, and there is no value in removing it. _shrug_

**Comment by phantomwhale** [comment]
Sorry, typed this whilst my brain stack was full of vim configurations - of course, JSXHint is a node plugin.

My feedback was really that on the Syntastic wiki, there is a link to a project who's opening paragraph is:

> Deprecated

> JSXHint is, and always was, a bad hack to make JSX lintable in the early days of React. It will always be inferior to proper linters like ESLint because it is not able to lint JSX or ES6 syntax, it instead compiles to ES5 then lints. You may get weird linter errors, especially with more involved transforms.

> Don't use JSXHint anymore if you can switch to ESLint.

So I wondered if anyone thought it might be worth updating the wiki recommendation to this project instead of the one that says "don't use me, use this other one instead" ?

Should Syntastic host recommendations on it's wiki at all, I don't know _shrug_. But it does, so I wondered if this one was worth updating?

**Comment by lcd047** [comment]
> Should Syntastic host recommendations on it's wiki at all, I don't know _shrug_. But it does, so I wondered if this one was worth updating?

Where exactly does syntastic "host recommendations on it's wiki"?  As far as I can tell, the wiki gives you information about how to run that particular checker, and what you can (and can't) do with it, all specific to syntastic.

**Comment by phantomwhale** [comment]
Ah right, sorry, totally got the context of these pages mixed up !

Apologies, I'll shut up now
