### ISSUE TITLE
[json files] Syntastic + jsonlint doesn't work

### ISSUE THREAD

**Issue by Asher256** [scrooloose/syntastic#1669]
Hi,

Syntastic didn't find any errors in my json files. 

I did a quick debug and I found why.

My operating system: Ubuntu 15.10
Package: apt-get install jsonlint
JSonlint version: jsonlint (demjson) version 2.2.2 (2014-06-25)
Syntastic version: the last git master branch (January 20, 2016)

This bug happened because in Ubuntu /usr/bin/jsonlint is not the node.js version of jsonlint, but the Python version (you can install it with: apt-get install python-demjson).
```
$ file /usr/bin/jsonlint
/usr/bin/jsonlint: Python script, ASCII text executable
```

There is another jsonlint in Ubuntu (apt-get install jsonlint): 
```
file /usr/bin/jsonlint-php 
/usr/bin/jsonlint-php: PHP script, ASCII text executable
```

In my case, the json filter failed because Syntastic tried to use --compact option (an option that doesn't exist in Python's jsonlint):
```
jsonlint file.json --compact
```

1st Suggestion: an automatic detection of the jsonlint version + different filters and options.

2nd Suggestion: replace npm/node.js's jsonlint and use the Python version in Syntastic (this jsonlint version is available in the majority of Linux distributions, because python-demjson is widely used).

Thank you.

Asher256

**Comment by lcd047** [comment]
The [relevant wiki page](https://github.com/scrooloose/syntastic/wiki/JSON%3A---jsonlint) makes it clear that it's `jsonlint` from [jsonlint.com](http://jsonlint.com/) that is supported, and not something else.  It's up to you to make sure that's what syntastic gets to see.  You can use `g:syntastic_json_jsonlint_exec` to tell syntastic to look for it under some other name, but you can't just replace `jsonlint` with some random executable and expect it to work. _shrug_

> 1st Suggestion: an automatic detection of the jsonlint version + different filters and options.

Sadly, `jsonlint --version` doesn't provide any identifier that would distinguish it from `demjson`, and the help text is subject to change.  On the other hand, `demjson` doesn't have any standard way to produce an unique name either.

> 2nd Suggestion: replace npm/node.js's jsonlint and use the Python version in Syntastic (this jsonlint version is available in the majority of Linux distributions, because python-demjson is widely used).

Then the majority of Linux distributions made a poor choice, since `demjson` doesn't provide enough information to make it usable by syntastic.  Example:
```
$ demjsonlint -v test.json 
test.json: unsupported escape code in JSON string literal: u'\\q",\n  "requireC...
```
As for the PHP one, I'm sure there are at least as many JSON linters out there as there are programming languages.  With some luck, most of them would also be imaginatively named `jsonlint`. :) If you absolutely must run one of these linters instead of the ones already supported by syntastic, and if it produces error messages in a useful format, then please feel free to post a PR.  The guid for writing syntastic checkers is [here](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide).
