### ISSUE TITLE
insecure mode on file

### ISSUE THREAD

**Issue by SkyLeach** [scrooloose/syntastic#1679]
```bash
________________________________________________________________________________
| ~/.vim/bundle/syntastic
| => find ./syntax_checkers/ -type f -perm 0777
./syntax_checkers//python/compile.py
```
global write/execute on a script file executed by an editor plugin

**Comment by SkyLeach** [comment]
Just one of the vulnerabilities (assuming syntastic available to sudo editing, but also valid for non-root user issues)
http://www.cvedetails.com/cve/CVE-2015-0926/

**Comment by lcd047** [comment]
> global write/execute on a script file executed by an editor plugin

That doesn't seem to be the case from where I'm standing:
```
$ git describe --tags
3.7.0-79-gcc440f1

$ git ls-tree HEAD -r | grep -v ^100644
100755 blob 730e60053d451311e96df85f7201cbbbfd73085e    syntax_checkers/erlang/erlang_check_file.erl
100755 blob 6e980c7b2b523f21378735b6284a4c4035c4fae3    syntax_checkers/python/codec.py
100755 blob 32f1413d4fa16e07e07136d3f3d47e26a1a4990b    syntax_checkers/python/compile.py
```
If you're seeing anything else the cause is either a glitch in `git`, or a problem on your side.

That said, syntastic is a development tool.  It isn't supposed to be run in a security-sensitive environment, let alone as root, and it makes no claim of security.  While I try to disarm the most obvious problems, it's a best effort approach, not a guarantee.  There has been no security audit of syntastic by any independent party (at least not as far as I know), and syntastic's main authors are not security experts.  So feel free to report any problem you see, but don't expect it to stop you from shooting yourself in your foot, or prevent malicious code from doing it.

> Just one of the vulnerabilities

If you mean to point out that third-party bundles like [`spf13`](https://github.com/spf13/spf13-vim) include syntastic and have it enabled by default, I'm with you on that: having syntastic installed automatically and enabled by default is a bad idea, to put it politely.

**Comment by SkyLeach** [comment]
I honestly have no idea.  I didn't check the git log before reporting this (I should have, but I wasn't thinking about validating the source).

I since checked it and the file mode in git is fine and there is no history for the file mode being incorrect in git.  Must have been something done on my end, but I have no idea what.  Probably an ID-10-T error when I was doing something with pathogen files.
