### ISSUE TITLE
Syntastic searches global node_modules instead of local project when using extends in .eslintrc

### ISSUE THREAD

**Issue by colbycheeze** [scrooloose/syntastic#1715]
When setting up an .eslintrc if you attempt to use the extends
```
{
  "extends": "airbnb"'
}
```

Everything will crash (silently, by simply not working)...this is assuming you have everything set up correctly within your local project node modules.

Apparently, syntastic will default to checking your `usr/local/lib/node_modules` instead of the local project node_modules.

You can hack around it by installing the config stuff globally, but that isn't a good way to do it when setting up lint settings for a team. Any ideas on how to get it to search for the local node_modules?

This issue was brought up in #1552

**Comment by colbycheeze** [comment]
Okay so update to this...apparently if I ONLY have the `.eslint` rules in the file it begins doing work, however when I use the "extends": "airbnb" rule everything stops working completely in syntastic checking.

This breaks everything
```
{
  "extends": "airbnb",
  // Custom Overrides
  "rules": {
    "quotes": [2, "single"]
  }
}
```

This works
```
{
  "rules": {
    "quotes": [2, "single"]
  }
}
```

**Comment by lcd047** [comment]
Does #1692 help?

**Comment by colbycheeze** [comment]
This is what got it for me.
```vim
" " Syntastic will search for an .eslintrc in your project, otherwise it defaults
autocmd FileType javascript let b:syntastic_checkers = findfile('.eslintrc', '.;') != '' ? ['eslint'] : ['standard']
" these 2 lines check to see if eslint is installed via local npm and runs that before going global
let s:eslint_path = system('PATH=$(npm bin):$PATH && which eslint')
let b:syntastic_javascript_eslint_exec = substitute(s:eslint_path, '^\n*\s*\(.\{-}\)\n*\s*$', '\1', '')
```

**Comment by lcd047** [comment]
... Until you try to open multiple files.  Glad it works for you though. :)

**Comment by colbycheeze** [comment]
What do you mean? How does it affect multiple files? Do you mean having more than one split open, or?

**Comment by lcd047** [comment]
Just open a second JavaScript file.  It doesn't matter how you do that: in a split, in a separate window or the same, in a separate tab or the same, or whatever.  Your `b:syntastic_javascript_eslint_exec` will be defined only for the first buffer.

Have you considered stopping for a moment and trying to understand what you're doing, rather than pasting together random bits from other people's posts?  Node is a mess that works (for suitable values of "works") thanks to of an even bigger mess of shell contraptions.  Perhaps you should try to follow the officially blessed way of doing things rather than try to emulate said contraptions in Vim?

**Comment by Arlefreak** [comment]
U just tried https://github.com/mysticatea/eslint-cli and worked as expected

**Comment by jimkang** [comment]
If you open a bunch of files like so `vim * */*`, it won't find the .eslintrc file.
