### ISSUE TITLE
Language checkers wiki page takes too long / doesn't reneder

### ISSUE THREAD

**Issue by benjaminfjones** [scrooloose/syntastic#1729]
The wiki page https://github.com/scrooloose/syntastic/wiki/Syntax-Checkers occasionally "takes too long to render" and so GitHub doesn't render it.

**Comment by benjaminfjones** [comment]
Perhaps this is GitHub's problem, since the wiki page doesn't actually have much content..

**Comment by lcd047** [comment]
Yes, GitHub seems to have scaling problems.  It isn't the first time syntastic gets hit, either.  A few month ago the same page listed all checkers together; nothing particularly complex, just a long list with links.  Then GitHub stopped rendering it, and I had to add the current indirection by language (cf. #1624, commit 281c811 to the [wiki](https://github.com/scrooloose/syntastic/wiki)).  In the mean time, people write open letters to GitHub demanding more features, while other people (or...? nah, that couldn't possibly...) keep DDoS-ing it.  I'm _sure_ this is going to end well. :)

Anyway, my options seem to be:

1. move syntastic elsewhere;
2. move everything except the [guide](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide) to the main repo.

The main candidate for moving syntastic would be Bitbucket, but that has its own set of problems.  There's also the problem of this issue tracker.

Moving the wiki pages to the main repo would involve converting everything from Markdown to Vim help.  Vim help has a lot less features, and there are basically no tools for munging it.  The conversion might take a while, too.

I'm open to suggestions.  In the mean time, I suppose you could clone the wiki and browse it locally:
```sh
git clone https://github.com/scrooloose/syntastic.wiki.git
```

**Comment by jasontibbitts** [comment]
Not to sound like some random advocate, but if if you have available server space, you could run a Pagure instance.  http://pagure.io/pagure

It's not quite github, but it's getting a heck of a lot closer.

**Comment by lcd047** [comment]
@jasontibbitts Thank you for this link, Pagure definitely looks better than some of the popular alternatives.  However, the problem is still what to do with the issue tracker.  There are more than 1k issues here (old PRs probably don't count), and while most are obsolete by now, there are some that can still help people solve various problems.  I suppose moving the wiki to the internal help would have to do for now (after I get to do the conversion, that is).

**Comment by rjframe** [comment]
I removed the bullet points and extra link info (`[[C|C]]` becomes `'[[C]]'), and it will render in the preview for me now, but still not in the page itself.

**Comment by lcd047** [comment]
@rjframe Thank you, it seems to work right now.  However, that page will only grow more complex in the future as checkers are added for more filetypes, and the result probably also depends on the load.  So I'll probably still have to at least convert the wiki, eventually if not right now.

**Comment by lcd047** [comment]
Ok, I moved checker docs from the wiki to the manual, only the changelog and the checker guide are left to the wiki.  Like I said, it took a while. :smile:

The result is not great since Vim help doesn't have as many features as Markdown, but all information should (hopefully) still be there.  The conversion was only partially automatic, so it's guaranteed to have bugs.  If you care about that, this might be a good time to look at the docs for your favourite checkers in `:h syntastic-checkers` and see if everything is ok.
