### ISSUE TITLE
Feature request: Textlint

### ISSUE THREAD

**Issue by bignimbus** [scrooloose/syntastic#1730]
[TextLint](https://github.com/textlint/textlint) is a natural-language linter for markdown, txt and (optionally) html files.  It would be great to support this tool in syntastic.

**Comment by lcd047** [comment]
Interesting stuff, thank you for the link.  Commit 9f766ea.

Textlint still has a few rough edges, and that translates to some shortcomings for syntastic.  F.i. it isn't possible to query the list of installed plugins, and a missing plugin doesn't trigger any useful exit code.  Consequently, there is no way for syntastic to tell whether the HTML plugin is installed, and when it isn't the checks will fail silently.  The fact that there is no way to debug what's going on doesn't help, either.  Still, the modular architecture of textlint might allow syntastic to interface with linters that it couldn't support otherwise.  Good find.
