### ISSUE TITLE
Compiling files when saving typescript files

### ISSUE THREAD

**Issue by MikaAK** [scrooloose/syntastic#1731]
My files are getting compiled and put in the same directory when I save a file using typescript. I have confirmed that uninstalling syntastic stops the files from spilling everywhere. Currently, say I save a file in  `myFolder/test/index.ts` it will create `myFolder/test/index.js`. This seems to be intermittent because reinstalling it is gone. In the past I have also experienced this and reinstalling fixed it that time too for a while.

**Comment by lcd047** [comment]
Syntastic is a Vim script, it can't produce JavaScript code.  What can produce code are the external checkers run by syntastic.  Open your test file and run `:SyntasticInfo`, to find out what checkers are run by syntastic.  Then set `g:syntastic_debug` to 1, run the checker, run `:mes`, and look for `getcwd()` and `makeprg` in the output, to find out how does syntastic run said checkers.  Then run the same commands in a terminal, and see whether they produce the offending files.  If they do, find a combination of options so that they no longer try to produce output.  Submit a PR if applicable.
