### ISSUE TITLE
typescript tsc checker does not respect tsconfig.json

### ISSUE THREAD

**Issue by adikari** [scrooloose/syntastic#1734]
I have few typescript projects with its own configs specified in `tsconfig.json`. However looks like tsc checker is not using them and displaying errors. 

My `tsconfig.json` includes some typing to allow the use of `require`. When I run `tsc` manually it reads the tsconfig where I included the typing to allow `require`. However syntactic is giving me error.

I have few other options specified in my tsconfig. One project has `target: ES5` and other has `ES6`. The current option to specify `--args` in vimrc will not work for me as these config would be different for each projects.

Bottomline: would be best if tsc would read the `tsconfig.json` of the project if it exists and use it. 

:SyntasticInfo
```
Syntastic version: 3.7.0-105 (Vim 704, Linux)
Info for filetype: typescript
Global mode: active
The current file will be checked automatically
Available checkers: tsc tslint
Currently enabled checkers: tsc tslint
```

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output (copy & paste the text please, no screenshots).

> Bottomline: would be best if tsc would read the `tsconfig.json` of the project if it exists and use it.

Syntastic is a Vim script, it doesn't know, nor care, about TypeScript, projects, or `tsconfig.json`.  What syntastic does is run `tsc` against your files and parses the output.  If `tsc` uses your `tsconfig.json`, the results will reflect that.  If `tsc` doesn't use your `tsconfig.json`, the results will reflect that, too.  If the results of running `tsc` from Vim differ from the results of of running it in a terminal, the problem is likely between Vim and your shell, and the above output should help finding it.

**Comment by lcd047** [comment]
No feedback, no cry.

**Comment by faceleg** [comment]
`tsc` seems to ignore `tsconfig.json` unless it's told to look for it with the argument `-p tsconfig.json`, see https://github.com/Microsoft/TypeScript/issues/5858

I'll see what I can do to hack support for this into the tsc checker.

**Comment by lcd047** [comment]
@faceleg Please see #1739.

**Comment by faceleg** [comment]
Agree

**Comment by jphustman** [comment]
I know this is closed, but I agree it should default to...
```let g:syntastic_typescript_tslint_args = "--config ~/tslint.json"```
