### ISSUE TITLE
Search up directory for javac config file

### ISSUE THREAD

**Issue by jdloft** [scrooloose/syntastic#1745]
As described in [this SO thread](https://stackoverflow.com/questions/18990636/how-to-make-syntastic-search-for-javac-config-file-in-project), javac config files aren't always going to be in the current working directory because of normal project browsing (who edits their files referencing them relative to their projects base directory?). It would make sense to have Syntastic parse up the directory structure until it finds a javac config file. Parameters such as the classpath would also need to be referenced relative to this file.

**Comment by lcd047** [comment]
Set `g:syntastic_java_javac_config_file_enabled` to 1, and set `g:syntastic_java_javac_config_file` to a full path, rather than a single filename.  Use `autocmd` to point `g:syntastic_java_javac_config_file` to different files for different projects.

Could this be made more user-friendly?  Sure, there's always room for improvement.  However, syntastic is a generic framework for checkers, not a checker specifically targeting Java.  It has no idea about projects and the like.  Also, `javac` is anything but friendly to command-line applications, which makes this checker an order of magnitude more complex than the next most complex checker in syntastic.  It sucks, and it would still suck no matter how much I'd try to improve it.  You are strongly advised to use an IDE such as Eclipse instead of syntastic for anything more complex than toy Java projects. _shrug_
