### ISSUE TITLE
Python Pylint Syntax Errors

### ISSUE THREAD

**Issue by Integralist** [scrooloose/syntastic#1755]
## Setup

I'm using NeoVim (installed via Homebrew) on my Mac (`10.11.4`).

I'm using `virtualenv` to activate Python3 by default in my shell. 

I've also set the following value in my `.vimrc`:

```viml
let g:syntastic_python_python_exec = "/usr/local/bin/python3"
```

## Problem

The issue I'm having is if I open a Python file that contains the following code...

```py
print("abc")
```

...I'll get the following error...

```
foo.py|1 col 1 warning| [superfluous-parens] Unnecessary parens after 'print' keyword 
```

Now I know that this is a Python2 warning and not a Python3 warning. So I can just ignore it, but how do I prevent it from being incorrectly reported in the first place? 

I've already configured Syntastic to use my Python3 interpreter via `syntastic_python_python_exec`, so it shouldn't even bother displaying this particular warning when I open the file.

## Things I've tried...

> Note: these weren't attempts at _solutions_,
> I was just trying different things to see what effect they had

First I removed the extra parenthesis and I see the error about the parentheses is replaced with:

```
foo.py|1 col 11 error| Missing parentheses in call to 'print'
```

So this suggests that my Syntastic change in my `.vimrc` to use Python3 must be having an effect (as I'd expect it to warn me that my `print` statement is no longer a statement in Python3 and is actually a function so it expects parentheses to be used).

I then decide to switch the interpreter explicitly to Python2 `:let g:syntastic_python_python_exec = "/usr/bin/python"` and this causes the error to disappear completely (again, as expected when using Python2).

## Other plugins causing odd side effects maybe?

So I have the following plugin installed:

- `nvie/vim-flake8`

> Full dotfiles can be found here: https://github.com/integralist/dotfiles

But when I uninstalled this plugin it made no difference to the outcome

**Comment by lcd047** [comment]
> I'm using NeoVim (installed via Homebrew) on my Mac (`10.11.4`).

NeoVim is not explicitly supported by syntastic, but it should work (mostly).

> I'm using `virtualenv` to activate Python3 by default in my shell.

Then install Pylint in the same environment, run Vim from it, and things should be consistent.  Don't expect syntastic to know anything about `virtualenv`, even if you're using `vim-virtualenv` or similar.  These can't work with syntastic, because of limitations in Vim.

> `let g:syntastic_python_python_exec = "/usr/local/bin/python3"`

This only affects the `python` checker.  It's irrelevant to the `pylint` checker.

> `foo.py|1 col 1 warning| [superfluous-parens] Unnecessary parens after 'print' keyword `

This looks like a message from the `pylint` checker.

> I've already configured Syntastic to use my Python3 interpreter via `syntastic_python_python_exec`, so it shouldn't even bother displaying this particular warning when I open the file.

No, the `pylint` checker doesn't care about `syntastic_python_python_exec`.  Either install a Python3 version of Pylint and point `syntastic_python_pylint_exec` to it, or simply install Pylint in `virtualenv` and run Vim from the virtual environment.

> `foo.py|1 col 11 error| Missing parentheses in call to 'print'`

This looks like a message from the `python` checker.  You might want to read `:h syntastic-filetype-checkers` and `:h syntastic-aggregating-errors`.

> I then decide to switch the interpreter explicitly to Python2

There is no such thing as a global switch between Python2 and Python3.  Syntastic doesn't know, nor care, about Python dialects and the like.  It only knows about running (external) binaries.  For each checker you can tell syntastic which binary to run (the `syntastic_python_*_exec` variables), or you can arrange for it to find the appropriate binaries in `$PATH` (the `virtualenv` way).  That's essentially all there is to it.

**Comment by Integralist** [comment]
Closing this issue as I've found a more appropriate way to solve my problem by switching to `pyenv` which is a lot less complicated to setup and requires no configuration on my part.
