### ISSUE TITLE
Racket checker runs GUI program

### ISSUE THREAD

**Issue by kasbah** [scrooloose/syntastic#1773]
With vim-racket installed, working on [a GUI program](https://gist.github.com/kasbah/13457814537438de5ac916127fe912bf), the racket checker runs the GUI program, `:make` does not.

vim-racket sets:
```
setl makeprg=raco\ make\ --\ %
```
which might be a better option for the checker. I couldn't find where to define the actual checker as [this line seems sort of magical](https://github.com/scrooloose/syntastic/blob/dac07db61758590c71d655ed5403181af4e845a2/syntax_checkers/racket/racket.vim#L23).

**Comment by lcd047** [comment]
Syntastic doesn't use, nor care about, Vim's option `makeprg`, Vim's command `:make`, and their friends.  It used to do that, but it stopped doing it a few years ago.  The name of the internal variable `makeprg` is a legacy from those days.  It's still a command line that gets passed to a shell eventually, but other than that it could have been any other name, it has no relation to Vim's `makeprg`.

Back to your problem: you can _see_ the command lines constructed by syntastic in the debug logs (see `:h syntastic-config-debug`).  By default, the `racket` checker simply runs `racket file.rkt`, and parses the output into a loclist with `lgetexpr`.  Unsurprisingly, this just runs the program.

You can _change_ the command line constructed by syntastic by setting the various options (see `:h syntastic-config-makeprg`).  Changing the command line to `raco make -- file.rkt` is unlikely to work though, since `lgetexpr` expects the output of `racket`, not that of `make`.  It's up to you to make sure syntastic runs something that makes sense.

**Comment by kasbah** [comment]
Thank you very much for the explanation. Do you not think the checker should be changed if it actually executes the program under test? Would you be so kind as to point me to where the executed command is defined in the syntastic source code?

**Comment by lcd047** [comment]
> Do you not think the checker should be changed if it actually executes the program under test?

Can `racket` check syntax of a (single) file without running it?  If it can, I can try to fix the sources.  If it can't, I can [wash my hands](https://github.com/scrooloose/syntastic/wiki/Perl%3A---perl#user-content-security) of it.  If the answer involves `raco make` then the fix might be more involved, and you'll have to explain me in some detail what is supposed to be going on (keeping into account that I barely know what Racket is, let alone how it works).

@2sb18 Any comments on this?

> Would you be so kind as to point me to where the executed command is defined in the syntastic source code?

It's [here](https://github.com/scrooloose/syntastic/blob/c2c6a075113adbfcc4f1ad5b1c0200a0d35ceeb6/syntax_checkers/racket/racket.vim#L23).  See the [guide](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#makeprgbuildoptions) and the [manual](https://github.com/scrooloose/syntastic/blob/c2c6a075113adbfcc4f1ad5b1c0200a0d35ceeb6/doc/syntastic.txt#L779-L806) for an explanation.

**Comment by lcd047** [comment]
Ok, assuming the worst.  Commit 95879f1.

**Comment by kasbah** [comment]
Probably for the best. I will try out the alternative racket checker and try and define one based on `raco make` if I am not happy with that one.
