### ISSUE TITLE
Is Syntastic supported in Neovim?

### ISSUE THREAD

**Issue by Daniel-M** [scrooloose/syntastic#1789]
Before trying anything on a Neovim installation I wonder if syntastic would be supported on the vim fork Neovim. I'm placing a issue since I haven't found a proper channel to put my question.

Thanks in advance

**Comment by lcd047** [comment]
Syntastic should work with Neovim, but it isn't "officially" supported.  Meaning, if you report a problem I'll try to address it only if I can reproduce it under plain Vim.  Also, syntastic might eventually support async checking (once Vim's API for job control gets stable), and when / if that happens the async functionality will use Vim's API rather than Neovim's.  However, [neomake](https://github.com/neomake/neomake) offers async checking today, and it (only) works with Neovim.

**Comment by Daniel-M** [comment]
I thought i wasn't supported at all. I'll give a try to neomake (the name is not suggesting about the syntactic completion though). Thanks for your answer!
