### ISSUE TITLE
ESLint syntax checker ignores `.eslintignore`

### ISSUE THREAD

**Issue by rhys-vdw** [scrooloose/syntastic#1791]
When I open files ignored by my project's `.eslintignore` errors and warnings are still highlighted. These errors will not be reported by running `eslint` directly.

Disclaimer: I have very little understanding how how all the pieces of this project fit together.

**Comment by lcd047** [comment]
Unless configured otherwise, syntastic runs `eslint -f compact file.js` and shows you whatever errors `eslint` produces.  When `file.js` is in your `.eslintignore` and you run `eslint` against it you get back a message telling you the file is ignored, and that's what syntastic should show you.  If you get something else then `eslint` is not run the way you believe it is.  You can _see_ what syntastic is doing in the debug logs (`:h syntastic-config-debug`).  You can _change_ what syntastic is doing by setting the apropriate options (`:h syntastic-config-makeprg`).

If you don't want syntastic to run checks automatically then set passive mode (see `:h :SyntasticToggleMode` and `:h 'syntastic_mode_map'`).  If you want syntastic to run checks automatically but skip certain files see `:h 'syntastic_ignore_files'`.  If you want syntastic to run checks but ignore certain errors see `:h 'syntastic_quiet_messages'`.

**Comment by rhys-vdw** [comment]
Right. This seems to be caused by a bad interplay between `:autochdir` and eslint's method of searching for `.eslintignore` (not traversing up the path). I'll open an issue with ESLint.

Thanks for the detailed response.

**Comment by rhys-vdw** [comment]
For anybody else interested in this issue, this is certainly not an issue with syntastic (it affects command line ESLint too).

I spoke to @ilyavolodin on Gitter regarding this issue. This is intentional behaviour of eslint as it has no way of determining 'project root' from a subdirectory. Previously this was supported (called "cascading" `.npmignore`), but was dropped due to a bad code complexity to usefulness ratio.
