### ISSUE TITLE
Is there a way to always display the status line and error indicator column, even when there are no errors?

### ISSUE THREAD

**Issue by mrdanimal** [scrooloose/syntastic#1796]
This is kind of an odd request, but I'd like to keep the statusline and error column open even when there are no warnings, because it's distracting to have the position of the split I'm editing move up and to the right every time there's a warning. If they were always there, the errors would display when they occurred, but the active split wouldn't move around.

**Comment by lcd047** [comment]
I presume by "error column" you mean the sign column (see `:h sign.txt`).

Keeping the sign column open has been requested several times in the past.  The answer has always been the same: the sign column is controlled by Vim, not by syntastic.  There is a workaround: you can trick Vim to keep the sign column open, by placing a sign past the end of the current buffer (again, do read `:h sign.txt`), and you can also do that from an `autocmd`.  But beware that placing too many signs can slow Vim to a crawl, and also some plugins will persist signs across sessions.  So you might also need to figure out how to remove the signs you placed when you're closing buffers.  It's a tricky problem, and syntastic has no reason to go there.

On the other hand, there are plugins that will happily show you all sorts of things in the sign column, and by that keep it open.  An example that comes to mind is [signature](https://github.com/kshenoy/vim-signature).  It's one of the better ones, it might work for you.

As for the statusline flag, you're the first to ask to keep it always on.  It can be done, but you'll need to understand the statusline machinery (see `:h 'statusline'`), and fight your way through it.

If you followed the manual and added `%{SyntasticStatuslineFlag()}` to your Vim's `statusline`, first you'll need to set `syntastic_stl_format` not to use `%E{...}`, `%W{...}`, or `%B{...}` (see `:h 'syntastic_stl_format'` for details).  This would take care of showing you the counts of errors and warnings even when they are zero, but syntastic will still kill the entire flag if there is nothing to report.  For this reason, you'll need to write a wrapper function around `SyntasticStatuslineFlag()` that returns your fixed string when `SyntasticStatuslineFlag()` returns empty.  Doing this might trigger various redraw problems, and you'll have to figure out how to solve them (again, redraws are controlled by Vim, not by syntastic).  Finally, if you're using a plugin that changes the statusline you'll also have to tell it about what you're doing.  This is another tricky problem, and again, syntastic has no reason to go there (since everything else wants to handle flags the other way around, for performance reasons). :shrug:

**Comment by mrdanimal** [comment]
Thanks for such a detailed answer! Extremely helpful. I guess I didn't know the right name for the sign column, so all the searching I did came up blank. I'll close the issue and try some of the things you suggest. Thanks again.
