### ISSUE TITLE
Bad performance with g:syntastic_python_flake8_quiet_messages

### ISSUE THREAD

**Issue by rpdelaney** [scrooloose/syntastic#1854]
My vimrc[[1]] has these lines in it (using vim-plug[[2]]):

```
Plug 'git://github.com/scrooloose/syntastic.git'
autocmd FileType python let g:syntastic_python_flake8_quiet_messages = { "type": "style", "regex": "ine too long" }
```

The idea is to suppress "line too long" warnings from flake8 in my python scripts.

However, whenever I save the file, I get several tedious seconds of lag where vim becomes unresponsive. Commenting the second line fixes that problem, but restores the warnings that I wanted to have suppressed.

Running flake8 on the file itself shows a moderate cost, but not as severe as I'm experiencing with syntastic:

```
$ time flake8 annotator.py
<snip>
real    0m0.555s
user    0m0.533s
sys     0m0.020s
```

Any suggestions for how I can troubleshoot the performance impact of `g:syntastic_python_flake8_quiet_messages`?

[1]: https://github.com/rpdelaney/dotfiles/blob/master/home/.vim/vimrc
[2]: https://github.com/junegunn/vim-plug

**Comment by lcd047** [comment]
Please read `:h syntastic-profiling`.  Enable profiling, upload the resulting logs somewhere, and post the link.

On a side note: your faith in `autocmd`s is heart-warming, but largely misplaced.  You might want to consider `filetype plugin indent on` and moving those per-filetype settings to `ftplugin` and `after/ftplugin` files.  There's also a set of recommended settings for syntastic, outlined in the manual.  But this is not what you asked, and they have only a minor contribution to your problem.

**Comment by rpdelaney** [comment]
Thanks for replying. Here's what I got from my attempt at invoking the profiler. I hope this helps: http://sprunge.us/RdDB

Can you point me toward further reading on why `autocmd` is deprecated?

**Comment by lcd047** [comment]
You traced the startup, which is useless:
```
FUNCTION  <SNR>70_CacheErrors()
Called 0 times
```
You have to get a trace of what happens when you see the delay.  Please re-enable profiling, do whatever you're doing to trigger the delay, and then post the logs.

> Can you point me toward further reading on why `autocmd` is deprecated?

It isn't _deprecated_, it's just that what you're doing is bad practice.  `autocmd`s are useful, but they are fragile, inefficient, and they can accumulate resource-eating garbage at high rates.  `ftplugin`s are much better from that point of view because they avoid some of the main problems.  Doing the same manually is possible, but highly nontrivial.

People who use `FileType` `autocmd`s to set options typically do so because they tried the `ftplugin`s way, they didn't like the defaults, and they were frustrated by the fact that you can't override `ftplugin` defaults by setting things in vimrc.  The way to do that is to add overrides to `after/ftplugin` files, but said people never got to read that part of the manual. _shrug_

**Comment by rpdelaney** [comment]
> You traced the startup, which is useless

Odd, I was pretty sure I had captured the problem behavior. Here, I'll do it again and list the steps:

1. Added this to the top of my .vimrc:
```
profile start syntastic.log
profile! file */syntastic/*
```
2. Edited a python script where I've been observing the lag
3. Add some whitespace, delete the whitespace, save the file, ZQ
4. `curl -F 'sprunge=<-' http://sprunge.us < syntastic.log`
5. http://sprunge.us/KWhf

**Comment by lcd047** [comment]
Ok, you traced the checker this time.  However, according to your logs the problem is not in syntastic:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.630972   0.000054  <SNR>70_BufWritePostHook()
    1   0.630889   0.000205  <SNR>70_UpdateErrors()
    1   0.627874   0.000747  <SNR>70_CacheErrors()
    4   0.611978   0.001001  syntastic#util#system()
    2   0.603803   0.000057  15()
    2   0.603513   0.000438  14()
    2   0.592538   0.002687  SyntasticMake()
    1   0.554579   0.003250  SyntaxCheckers_python_flake8_GetLocList()
    1   0.042930   0.000055  SyntaxCheckers_python_python_GetLocList()
    3   0.018412   0.001125  88()
    2   0.011927   0.000059  20()
    1   0.011704   0.000040  SyntaxCheckers_python_python_IsAvailable()
    1   0.011636   0.000065  16()
   13   0.011352   0.000495  79()
    1   0.009759   0.000072  80()
    2   0.004108   0.001041  25()
    2   0.004054   0.000847  75()
   36   0.003067   0.000418  SyntaxCheckers_python_flake8_GetHighlightRegex()
    1   0.002878   0.000482  <SNR>70_BufEnterHook()
   36   0.002649             SyntaxCheckers_python_pyflakes_GetHighlightRegex()
```
`BufWritePostHook()` calls `UpdateErrors()`, which calls `CacheErrors()`, which calls `SyntasticMake()`, which finally calls `syntastic#util#system()`.  It happens here, and you see it spending ~0.58s running `flake8 --version` and `flake8` (which is consistent with what you measured in a terminal), and basically no time in Vim:
```
    2   0.589740   0.000103     let err_lines = split(syntastic#util#system(a:options['makeprg']), "\n", 1)
```
That's nowhere near several seconds, so your problem is elsewhere, probably in another plugin, in an `autocmd` on write not shown in the config you posted above, or in some other code that comes into play for non-obvious reasons.  Either way it has nothing to do with syntastic.

One way forward from here would be to get a profile log for everything.  Another way would be to disable the other plugins in turn (disable half of them, then the other half etc.) to try to locate the culprit.  Finally, Vim might be running code you aren't aware of (there were reports in the past of people running Eclim without being aware of it).

**Comment by rpdelaney** [comment]
In case anyone comes here with a similar issue, I solved the problem by dropping `g:syntastic_python_flake8_quiet_messages` and adding these options instead:

```
  autocmd FileType python let g:syntastic_python_checkers = ['flake8']
  autocmd FileType python let g:syntastic_python_flake8_post_args = '--ignore=E501,E241'
```

**Comment by lcd047** [comment]
For what it's worth, `quiet_message` filtering takes 0.001357s according to your test:
```
    2   0.001357   0.000024     call self._quietMessages(list)
```
The delay you're accusing is definitely not spent there. _shrug_
