### ISSUE TITLE
Sytnastic does not enable eslint plugin for react files.

### ISSUE THREAD

**Issue by sheki** [scrooloose/syntastic#1856]
In the same code base syntastic/eslint works for a pure js file. It fails for a file with react/jsx.

These are my syntastic logs
https://gist.github.com/sheki/74c173629fa2bf61f40a12645b9bbd77

**Comment by lcd047** [comment]
That's because you're using one of the (many) broken hacks to run a local `eslint`, which only covers the filetype `javascript`, not `javascript.jsx`. _shrug_

Thew recommended way to do it is to either install [eslint-cli][eslint-cli], or add `eslint` as a linter as in #1692.

[eslint-cli]: https://github.com/mysticatea/eslint-cli
