### ISSUE TITLE
Changes in Syntastic broke fsharp-vim

### ISSUE THREAD

**Issue by Kazark** [scrooloose/syntastic#1893]
cc @kjnilsson

I just updated all my Vundle dependencies, and the F# checker registered by the [F# plugin](https://github.com/fsharp/vim-fsharp) stopped working. The F# plugin had also updated, so I reset it to a known state, and it still didn't work, so I put it back to its current state and reset this plugin to a state from about a week ago. It worked, so I used the beautiful `git bisect` command to determine that [this](https://github.com/scrooloose/syntastic/commit/adf899f1ba863b1ea2c3327e7cde79ba21354435) was the breaking change:

    adf899f1ba863b1ea2c3327e7cde79ba21354435 is the first bad commit
    commit adf899f1ba863b1ea2c3327e7cde79ba21354435
    Author: LCD 47 <lcd047@gmail.com>
    Date:   Sun Oct 9 11:08:06 2016 +0300

        Refcator registry code.

        It is now possible to run checkers for a filetype different than the
        filetype of the current file.

    :100644 100644 1cf31e6f6baf957eedac231eec66618d78f318e7 e3e07687a7a422b53ab38d80bb8043dbd9c3c2f8 M  README.markdown
    :040000 040000 7ec0047af1e0a76f80e1e35a870fc8cf884fb554 0b0bcd519504f49cabb919c1a766427d2d712d19 M      doc
    :040000 040000 6243bc479fdc05785b8eb1910fd7b685510ee590 fbdf928d88847aa5826ec24fb33d9b834f6e6f2d M  plugin

Also, the rest of the F# plugin's functionality worked; only it's Syntastic integration didn't work. `:SyntasticInfo` showed that it wasn't working:

    Syntastic version: 3.7.0-234 (Vim 800, Windows)
    Info for filetype: fsharp
    Global mode: active
    Filetype fsharp is active
    The current file will be checked automatically
    Available checker: syntax
    Currently enabled checkers: -

As you can see, the currently enable checkers was disabled.

Running on Windows 7 with VS 2013/F# 3.1 installed, if that matters. Also Vim 8.0.

**Comment by Kazark** [comment]
In case it makes any difference, here is the entire bisect log:

    # bad: [90e96d445fef4cdf0d010df642076832d3571c32] Bug fix: handling foreign checkers in "*_checkers" lists.
    # good: [3ea6924aace91ab3b6878ec5a7b9b6e28b242f5f] Bug fix: further relax syntastic#util#fname2buf().
    git bisect start 'HEAD' '3ea6924'
    # good: [e7d1fe75d45457e5f124ac797c5ca06ea5db48ae] README: minor fixes.
    git bisect good e7d1fe75d45457e5f124ac797c5ca06ea5db48ae
    # good: [4c4e516e1ddd7c1b04624e26be1bbb41bc6b7edb] Bug fix: allow checkers to have an empty exec.
    git bisect good 4c4e516e1ddd7c1b04624e26be1bbb41bc6b7edb
    # good: [1379530f03e1169ff8120f306b3a193b9228590e] New checker for HTML: htmlhint.
    git bisect good 1379530f03e1169ff8120f306b3a193b9228590e
    # bad: [753ed1fbe96bc734a588041f9afb830542aad4d3] Minor fixes.
    git bisect bad 753ed1fbe96bc734a588041f9afb830542aad4d3
    # bad: [adf899f1ba863b1ea2c3327e7cde79ba21354435] Refcator registry code.
    git bisect bad adf899f1ba863b1ea2c3327e7cde79ba21354435
    # first bad commit: [adf899f1ba863b1ea2c3327e7cde79ba21354435] Refcator registry code.

**Comment by lcd047** [comment]
> As you can see, the currently enable checkers was disabled.

Not sure why you're reporting this here.  This "problem" can be fixed by you reading the manual, or even the [FAQ](https://github.com/scrooloose/syntastic#faqinfo).  From the [FAQ]([FAQ](https://github.com/scrooloose/syntastic#faqinfo):

> A second probable reason is that none of the available checkers are
enabled. Syntastic comes preconfigured with a default list of enabled checkers
per filetype, but this list is kept short in order to prevent slowing down Vim
or trying to run conflicting checks. The command `:SyntasticInfo` will show you
which checkers are enabled. You can tell syntastic which checkers (among the
available ones) you want to run by setting `g:syntastic_<filetype>_checkers` in
your `vimrc` (see [below](https://github.com/scrooloose/syntastic#faqcheckers)).

That said, the checker is not innocent, either.  It doesn't follow the [guidelines](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#external) to add a `g:syntastic_extra_filetypes`, and its [availability check](https://github.com/fsharp/vim-fsharp/blob/master/syntax_checkers/fsharp/syntax.vim#L10) is too generic to be useful.  But this only means it will break with the next version of syntastic.  It has nothing to do with your problem.

**Comment by kjnilsson** [comment]
@Kazark feel free to raise and cross reference this for fsharp-vim instead. There is obviously some work to be done there.

**Comment by Kazark** [comment]
@kjnilsson @lcd047 Okay, thanks. I assumed this was the right place to report it, since Syntastic was the thing that had changed. I will report at fsharp-vim instead.
