### ISSUE TITLE
feature request: syntax check support for Python 3

### ISSUE THREAD

**Issue by stardiviner** [scrooloose/syntastic#283]
Just like the title write, I hope Syntastic support Python 3.

**Comment by benjaminbrent** [comment]
**Note** you should actually be setting `g:syntastic_python_python_exec`, NOT `g:syntastic_python_python_exe` (as per [here](https://github.com/scrooloose/syntastic/issues/1306#issuecomment-71158539)):

```vim
let g:syntastic_python_python_exec = 'python3'
```

**Comment by lcd047** [comment]
Using `g:syntastic_python_python_exe` was appropriate at the time; it no longer is for recent versions of syntastic.  Which is why you should read the [manual](https://github.com/scrooloose/syntastic/blob/79007b01f2f0e70482ee288bafc31f58dbaad5a1/doc/syntastic.txt#L670-L742), or at least the [FAQ](https://github.com/scrooloose/syntastic#faqpython3) before searching the archives: old advice might be outdated.

**Comment by benjaminbrent** [comment]
@lcd047 Indeed. Unfortunately this is the first result on Google when searching for "python3 syntastic", so it's probably worthwhile making the point explicitly.

**Comment by lcd047** [comment]
There also seems to be a widespread confusion about it on StackOverflow.  The `exe` thing is rarely useful outside syntastic code itself, it should probably be renamed to something else.  Sadly doing so would break a few third-party checkers, and checking syntastic version to is also awkward, for similar historic reasons.
