### ISSUE TITLE
Is there a way to get Syntastic working without saving the file.

### ISSUE THREAD

**Issue by symbolix** [scrooloose/syntastic#669]
Hi,
I have just installed Syntastic on MacVim and configured it to work with pyflakes. All critical config is in my .vimrc file, so the plugin works. However, I would like to be able to invoke the plugin check and the error display functions without saving the file. Well I did things like:

map <silent> <F12> :w<CR>:Errors<CR>
imap <silent> <F12> <ESC>:w<CR>:Errors<CR>

Which are supposed to make the process seamless, but still this is saving the file. Is there a way to get this working without actually saving the changes to the file. I thought the passive mode is designed for this?

map <C-F12> :w<CR>:SyntasticToggleMode<CR>
imap <C-F12> <ESC>:w<CR>:SyntasticToggleMode<CR>

So by switching the PASSIVE mode ON, I should be able to run the ":SyntasticCheck" and the ":Errors" manually, right? However that seems not to be able to update the results on the fly. The error reports and the signs are still there even after the mistakes are corrected. However once I run ":w", it all works again.

Any ideas? Thanks.

**Comment by guilala** [comment]
I think why @symbolix asks for that, or at least why i would like this to be possible; is in a Javascript environment. Popular Javascript build systems, like Grunt, often listen for file modifications, then automatically rebuild. When a build fails, because of a syntax error, such build process often exits. So to keep the build process running, you definitely want to know about syntax errors before you save the file. Therefore it would be very useful if Syntastic could check the buffer, not the file, automatically, after a few idle seconds...

**Comment by lcd047** [comment]
@guilala Sorry, syntastic can't do this.

At some point I made an experiment in that direction, and nobody cared (cf. #1351).  Reviving it would be easy, but that approach would only work for the (few) languages for which Vim has embedded interpreters: Perl, Python, Ruby, Lua, and perhaps TCL and MzScheme.  Extending it to JavaScript wouldn't be possible without a major re-design of syntastic, and would only work with major limitations.  Not going to happen, sorry.

**Comment by danijar** [comment]
@lcd047 I would really appreciate this behavior. Often, syntax errors depend on each other, so I have to save & re-check after fixing each error. How about automatically writing the buffer to a temporary file outside of the source tree and linting that?

**Comment by lcd047** [comment]
@danijar Nope: many linters run checks against the full project rather than against a single file.

**Comment by mandyzore** [comment]
Hi, you may wanna try [vim-auto-save](https://github.com/vim-scripts/vim-auto-save) ; it works for me on this need.

0. get the vim, syntactic, pylint ready to go
1. install Vundle to vim
2. add ```Plugin '907th/vim-auto-save'``` between the ```call vundle#begin()``` and ```call vundle#end() ``` lines in .vimrc
3. run ```vim +PluginInstall +qall ``` in command line
4. add ```let g:auto_save = 1``` to .vimrc, to enable the AutoSave on Vim startup
5. open a python in Vim and set ```:AutoSave``` on to test

**Comment by haberdashPI** [comment]
I think it's a little strange that you say syntastic "can't do this". It seems like there should be any number of fairly straightforward solutions to the problem: e.g. save the file to a temporary directory, and run linting on that temporary directory.

**Comment by lcd047** [comment]
@haberdashPI Did you read the thread above?

> save the file to a temporary directory, and run linting on that temporary directory.

What file?  As I said, many linters run checks against the full project rather than against a single file.  You may try copying the entire project locally, but Vim has no concept of project.

But even if the actual checks are against a single file, that doesn't mean there is a single file involved.  Consider f.i. `#include <foo.h>` in C.  The file `foo.h` may not even be part of the project.

Sadly, a solution that save files locally to check them would be half-assed at best. _shrug_
