### ISSUE TITLE
Disable syntastic on a buffer specific basis.

### ISSUE THREAD

**Issue by wting** [scrooloose/syntastic#689]
Some files I open for work need syntastic disabled since it takes 30-60 seconds to run. However there is no way to disable on a buffer specific basis, only to disable it globally.

I am aware of `syntastic_mode_map` and `passive_filetypes`, but the problem is I don't want to disable syntastic for all files of one type but files of one type in a specific directory.

This can also be mitigated if there was a `SyntasticEnable` and `SyntasticDisable` option. That way I could use the following:

`au BufNewFile,BufRead ~/work/* SyntasticDisable`

Right now with `SyntasticToggleMode` switches it on and off every time a new file is opened.

This alternative fix fails as well:

``` VimL
function! WorkSettings()
    let g:syntastic_mode_map = {
    \ 'mode': 'active'
    \ 'passive_filetypes': ['python']
    \ }
endfunction

au BufNewFile,BufRead ~/work/* call WorkSettings()
```

**Comment by ssteele** [comment]
Looks like it's been a while, but I came here with the same problem...

Because a few of the files I work on at my job are hopelessly non-PSR compliant, I was looking for functionality to turn off Syntastic for the current buffer only. The 'SyntasticDisableToggle' solution outlined [here](https://github.com/scrooloose/syntastic/issues/1361) works for me until I save, whereby the script variable 's:syntastic_disabled' is ignored and those non-PSR compliant files bog down all over again. This simplified approach works better for me:

```
"disable syntastic on a per buffer basis (some work files blow it up)
function! SyntasticDisableBuffer()
    let b:syntastic_mode = "passive"
    SyntasticReset
    echo 'Syntastic disabled for this buffer'
endfunction

command! SyntasticDisableBuffer call SyntasticDisableBuffer()
```

Like the original disabling function, this has no affect on other buffers in the current session.

**Comment by lcd047** [comment]
@ssteele The manual is your friend: `:h 'b:syntastic_skip_checks'`.

**Comment by oren0e** [comment]
Maybe related to here - each time I switch between buffers (code in rust) the SyntasticCheck appears in a new buffer, this is annoying. I want that only when I save this window will appear and the check will occur. How can I do that? This happens to me even if I set `let g:rustfmt_autosave = 0`

**Comment by lcd047** [comment]
@oren0e 
1. Syntastic is essentially dead, please consider using [ALE][ALE] instead;
2. Rust checkers are external checkers that are not part of syntastic;
3. Your best bet is probably to set `g:syntastic_auto_loc_list` to 0 (error window will be neither opened nor closed automatically).

[ALE]: https://github.com/dense-analysis/ale

**Comment by oren0e** [comment]
@lcd047 Thanks for your comments.
re point 3 - it disables the error window even when I save with `:w`, that's too much. I want it to open on save just not when I merely switch between buffers

**Comment by lcd047** [comment]
@oren0e Well like I said, syntastic is essentially dead.  But if you post a patch I'll consider it.
