### ISSUE TITLE
Syntastic not finding/setting the correct checker

### ISSUE THREAD

**Issue by RobertAudi** [scrooloose/syntastic#728]
I have been searching and trying to solve this issue for 2 days. Syntastic either uses the system ruby (ie 1.8.7) or nothing. By default it uses the system ruby even though I have rvm set up correctly. If I add any or all of the following lines to my `.vimrc` it doesn't load any checker:

```
let g:syntastic_ruby_exec = "~/.rvm/rubies/ruby-2.0.0-p247/bin/ruby"
let g:syntastic_eruby_checkers=['~/.rvm/rubies/ruby-2.0.0-p247/bin/ruby']
let g:syntastic_ruby_checkers=['~/.rvm/rubies/ruby-2.0.0-p247/bin/ruby']
```

How can I fix this problem please?

I am using Homebrew vim (not MacVim, terminal vim) on OS X Mountain Lion and I have the latest RVM with ruby 2.0.0 installed

**Comment by mooreniemi** [comment]
I think I'm probably doing something wrong. But I'm using `let g:syntastic_ruby_exec = '/Users/amooreniemi/.rvm/rubies/ruby-2.1.3/bin/ruby'` while editing a project that has a jruby .ruby-version file, and I am seeing `jruby 1.7.13 (1.9.3p392) 2014-06-24 43f133c on Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-466.1-11M4716 [darwin-x86_64]` when I run `:!ruby -v` in my vim session.

Am I overriding it incorrectly? What else can I do?

**Comment by mooreniemi** [comment]
Currently enabled checkers: mri jruby rubocop
syntastic: 133.948362: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = ''
syntastic: 133.948598: UpdateErrors: mri
syntastic: 133.948960: CacheErrors: mri
syntastic: 133.950288: g:syntastic_aggregate_errors = 0
syntastic: 133.950507: getcwd() = '/Users/amooreniemi/work/core-api/app/controllers'
syntastic: 133.950921: CacheErrors: Invoking checker: ruby/mri
syntastic: 133.951582: SyntasticMake: called with options: {'errorformat': '%-G%\m%.%#warning: %\%%(possibly %\)%\?useless use of == in void context,%-G%\%.%\%.%\%.%.%#,%-GSyntax OK,%E%f:%l: syntax error
\, %m,%Z%p^,%W%f:%l: warning: %m,%Z%p^,%W%f:%l: %m,%-C%.%#', 'makeprg': '/Users/amooreniemi/.rvm/rubies/ruby-2.1.3/bin/ruby -w -T1 -c locations_controller.rb', 'env': {'RUBYOPT': ''}}
syntastic: 134.099133: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = ''
syntastic: 134.099311: UpdateErrors (auto): default checkers
syntastic: 134.099408: _skip_file: skipping checks
syntastic: 134.168093: getLocList: checker ruby/mri returned 0
syntastic: 134.217112: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = ''
syntastic: 134.217257: UpdateErrors (auto): default checkers
syntastic: 134.217344: _skip_file: skipping checks

**Comment by lcd047** [comment]
> syntastic: 134.099408: _skip_file: skipping checks

Please open the same file, run `:SyntasticInfo`, and post the output.

**Comment by mooreniemi** [comment]
Syntastic version: 3.6.0-77 (Vim 703, Darwin)
Info for filetype: ruby
Global mode: active
Filetype ruby is active
The current file will be checked automatically

**Comment by lcd047** [comment]
This is not supposed to happen (that is, the code as written gives you an explanation when you run `:SyntasticInfo`).  Please see #1391 for details.

**Comment by mooreniemi** [comment]
@lcd047 Apologies, I don't quite follow. Unsure how #1391 relates. I _am_ seeing it check the file for any of the checkers I have installed on jruby, while I have _all_ of them installed in mri ruby. But despite setting `g:syntastic_ruby_exec` to mri ruby it's using jruby (I see in jps it boot up a JVM). Am I misunderstanding, and can I not actually override the checkers to use a different executable?

**Comment by mooreniemi** [comment]
@lcd047 My mistake I think, I see the output of the PATH identifies jruby as first in its list, so I am imagining that's why it uses it?

**Comment by lcd047** [comment]
_Sigh_ Let's start this again.

Syntastic has different checkers for the `eruby` and for `ruby` _filetypes_.  The initial post was about `eruby`, yours seems to be about `ruby`.

For the `ruby` filetype, there are different checkers `mri` (using plain `ruby`) and `jruby` (using `jruby`).  You shouldn't mix them, since they produce errors in different formats.

Set `g:syntastic_ruby_checkers` to tell syntastic what checkers you want to run (i.e. don't rely on defaults making sense for your situation).

You can tell the `mri` what binary to use by setting either `g:syntastic_ruby_mri_exec`, or by setting `g:syntastic_ruby_exec` (the latter is a legacy option, and it also sets the binary for the `eruby` checker).  Use this if you want to use a custom version of (plain) Ruby.  Don't point it to JRuby, or to anything else that isn't plain Ruby.

You can tell `jruby` what binary to use by setting either `g:syntastic_ruby_jruby_exec`.  Use this if you want to use a custom version of JRuby.  Don't point it to anything that isn't JRuby.

You also seem to have a problem with syntastic skipping files.  It's hard to tell what it is (or if indeed it's only a problem in my imagination) without _complete_ and _unmodified_ logs.

Last but not least: please don't hijack old threads.  If you aren't 100% sure your problem relates to an old issue please open a new one.  Start by explaining what you did, what did you expect to happen, and what happened instead.

**Comment by mooreniemi** [comment]
@lcd047 I understand your frustration, I can reopen elsewhere. No one will ever be 100% sure, but we can try to trust you to merge issues together rather than blob onto an old one. :) I appreciate your patience in answering my questions.

So you would not advise using non-jruby executable to check ruby files that aren't doing anything jruby-specific in them? (IME, unless I am inlining java, or my gem has a java extension vs c extension, or does threading etc, my runtime won't matter much to me. I've had to deploy ruby apps that supported both, god help me.) 

I guess my real issue is that JVM boot time makes the checkers so slow they're effectively useless to me, so unless I can stay attached to a running java process (I haven't thought about how I'd do that, fwiw) or use an mri executable (and again, for the vast majority of files, I would think that should be fine), I'll prob just switch this off.

Is there value in my opening an issue for attaching to an on-going JVM?

Thanks again.

**Comment by lcd047** [comment]
One more thing: the output of `:!ruby -v` is completely irrelevant to syntastic.

**Comment by mooreniemi** [comment]
I'm gonna say that prob not valuable to open an issue of attaching checkers to a running JVM for speed, but I think it'll be possible via drip or nailgun. (So for those googling and coming here, give that a try, and leave @lcd047 alone. :))

**Comment by lcd047** [comment]
1. I can't merge (or split) issues on Github.
2. You can use whatever (supported) checker you feel is appropriate, you just have to tell syntastic about what you want.
3. If it's possible to attach jruby to an already running JVM, I have no idea how to do it.  I actually know very little about Ruby, and nothing about JRuby.  Is this described anywhere?

**Comment by mooreniemi** [comment]
@lcd047 1. Only saying it makes sense to trust maintainers to link issues, not literally merge. :)

2. doesn't seem to be working for me, though my guess atm is just that while mri checks the more general variable and sets itself by that, jruby does not. (https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/ruby/mri.vim:22 vs https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/ruby/jruby.vim) I think once I set the specific jruby executable to be mri, (using the syntax you have in the manual etc) it'll be fine. I won't bother you with that. :)

3. I'm bugging the #jruby chat in freenode and they recommended: https://github.com/jruby/jruby/wiki/Improving-startup-time so I'm gonna try nailgun and drip.

**Comment by lcd047** [comment]
What exactly doesn't work?  Please read [my answer above](https://github.com/scrooloose/syntastic/issues/728#issuecomment-99100541).  If that doesn't solve your problem, please open a new issue.  Start by explaining what you did, what did you expect to happen, and what happened instead.
