### ISSUE TITLE
how can i hide all syntax error info?

### ISSUE THREAD

**Issue by g1ra** [scrooloose/syntastic#748]
Its is very neat, i can do syntax check . 
with
":SyntasticCheck

But how can I hide (turn off) all result. ?

**Comment by TechWiz-3** [comment]
Is there a way to hide them line by line like in vscode with the `type: ignore` comment?

**Comment by lcd047** [comment]
@TechWiz-3 No.  Syntastic uses standard Vim `loclist`s, which don't work like that.  In principle you could create a macro to hide lines from the current `loclist`, but that won't work with syntastic because syntastic maintains several other data structures that need to be in synch with said `loclist`.  So no, there is no reasonable way to do that.

**Comment by TechWiz-3** [comment]
That's ok, thanks for letting me know 👍
